// Auto-generated by generate.py — do not edit

import type { ELEMENT_NAMES, REQUIRED_ATTRIBUTES } from './constants.generated'

export type AvailableElement = (typeof ELEMENT_NAMES)[number]

export type AttributesANY = {}

export type AttributesANY_BIT = {}

export type AttributesANY_DATE = {}

export type AttributesANY_DERIVED = {}

export type AttributesANY_ELEMENTARY = {}

export type AttributesANY_INT = {}

export type AttributesANY_MAGNITUDE = {}

export type AttributesANY_NUM = {}

export type AttributesANY_REAL = {}

export type AttributesANY_STRING = {}

export type AttributesBOOL = {}

export type AttributesBYTE = {}

export type AttributesComment = {
	'xsi:type'?: 'edgeModifierType' | 'storageModifierType' | (string & {})
}

export type AttributesDATE = {}

export type AttributesDINT = {}

export type AttributesDT = {}

export type AttributesDWORD = {}

export type AttributesFBD = {}

export type AttributesIL = {}

export type AttributesINT = {}

export type AttributesLD = {}

export type AttributesLINT = {}

export type AttributesLREAL = {}

export type AttributesLWORD = {}

export type AttributesREAL = {}

export type AttributesSFC = {}

export type AttributesSINT = {}

export type AttributesST = {}

export type AttributesTIME = {}

export type AttributesTOD = {}

export type AttributesUDINT = {}

export type AttributesUINT = {}

export type AttributesULINT = {}

export type AttributesUSINT = {}

export type AttributesWORD = {}

export type AttributesaccessVariable = {
	alias: string
	direction?: 'readOnly' | 'readWrite' | (string & {})
	instancePathAndName: string
}

export type AttributesaccessVars = {
	constant?: string
	name?: string
	nonpersistent?: string
	nonretain?: string
	persistent?: string
	retain?: string
}

export type Attributesaction = {
	globalId?: string
	name: string
}

export type AttributesactionBlock = {
	executionOrderId?: string
	globalId?: string
	height?: string
	localId: string
	negated?: string
	width?: string
}

export type Attributesactions = {}

export type AttributesaddData = {}

export type AttributesaddDataInfo = {}

export type AttributesalternativeText = {}

export type Attributesarray = {}

export type AttributesarrayValue = {}

export type AttributesbaseType = {}

export type Attributesblock = {
	executionOrderId?: string
	globalId?: string
	height?: string
	instanceName?: string
	localId: string
	typeName: string
	width?: string
}

export type Attributesbody = {
	WorksheetName?: string
	globalId?: string
}

export type Attributescoil = {
	edge?: 'none' | 'falling' | 'rising' | (string & {})
	executionOrderId?: string
	globalId?: string
	height?: string
	localId: string
	negated?: string
	storage?: 'none' | 'set' | 'reset' | (string & {})
	width?: string
}

export type Attributescomment = {
	globalId?: string
	height: string
	localId: string
	width: string
}

export type Attributescondition = {
	negated?: string
}

export type AttributesconfigVariable = {
	address?: string
	instancePathAndName: string
}

export type AttributesconfigVars = {}

export type Attributesconfiguration = {
	globalId?: string
	name: string
}

export type Attributesconfigurations = {}

export type Attributesconnection = {
	formalParameter?: string
	globalId?: string
	refLocalId: string
}

export type AttributesconnectionPointIn = {
	globalId?: string
}

export type AttributesconnectionPointOut = {
	globalId?: string
}

export type AttributesconnectionPointOutAction = {
	formalParameter: string
	globalId?: string
}

export type Attributesconnector = {
	globalId?: string
	height?: string
	localId: string
	name: string
	width?: string
}

export type Attributescontact = {
	edge?: 'none' | 'falling' | 'rising' | (string & {})
	executionOrderId?: string
	globalId?: string
	height?: string
	localId: string
	negated?: string
	storage?: 'none' | 'set' | 'reset' | (string & {})
	width?: string
}

export type Attributescontent = {}

export type AttributescontentHeader = {
	author?: string
	language?: string
	modificationDateTime?: string
	name: string
	organization?: string
	version?: string
}

export type Attributescontinuation = {
	globalId?: string
	height?: string
	localId: string
	name: string
	width?: string
}

export type AttributescoordinateInfo = {}

export type Attributesdata = {
	handleUnknown: 'preserve' | 'discard' | 'implementation' | (string & {})
	name: string
}

export type AttributesdataType = {
	name: string
}

export type AttributesdataTypes = {}

export type Attributesderived = {
	name: string
}

export type Attributesdescription = {}

export type Attributesdimension = {
	lower: string
	upper: string
}

export type Attributesdocumentation = {}

export type Attributesenum = {}

export type Attributeserror = {
	globalId?: string
	height: string
	localId: string
	width: string
}

export type Attributesexpression = {
	'xsi:type'?: 'edgeModifierType' | 'storageModifierType' | (string & {})
}

export type AttributesexternalVars = {
	constant?: string
	name?: string
	nonpersistent?: string
	nonretain?: string
	persistent?: string
	retain?: string
}

export type Attributesfbd = {}

export type AttributesfileHeader = {
	companyName: string
	companyURL?: string
	contentDescription?: string
	creationDateTime: string
	productName: string
	productRelease?: string
	productVersion: string
}

export type AttributesglobalVars = {
	constant?: string
	name?: string
	nonpersistent?: string
	nonretain?: string
	persistent?: string
	retain?: string
}

export type AttributesinOutVariable = {
	edgeIn?: 'none' | 'falling' | 'rising' | (string & {})
	edgeOut?: 'none' | 'falling' | 'rising' | (string & {})
	executionOrderId?: string
	globalId?: string
	height?: string
	localId: string
	negatedIn?: string
	negatedOut?: string
	storageIn?: 'none' | 'set' | 'reset' | (string & {})
	storageOut?: 'none' | 'set' | 'reset' | (string & {})
	width?: string
}

export type AttributesinOutVariables = {}

export type AttributesinOutVars = {
	constant?: string
	name?: string
	nonpersistent?: string
	nonretain?: string
	persistent?: string
	retain?: string
}

export type AttributesinVariable = {
	edge?: 'none' | 'falling' | 'rising' | (string & {})
	executionOrderId?: string
	globalId?: string
	height?: string
	localId: string
	negated?: string
	storage?: 'none' | 'set' | 'reset' | (string & {})
	width?: string
}

export type Attributesinfo = {
	name: string
	vendor: string
	version?: string
}

export type AttributesinitialValue = {}

export type Attributesinline = {
	WorksheetName?: string
	globalId?: string
}

export type AttributesinputVariables = {}

export type AttributesinputVars = {
	constant?: string
	name?: string
	nonpersistent?: string
	nonretain?: string
	persistent?: string
	retain?: string
}

export type Attributesinstances = {}

export type Attributesinterface = {}

export type Attributesjump = {
	executionOrderId?: string
	globalId?: string
	height?: string
	label: string
	localId: string
	width?: string
}

export type AttributesjumpStep = {
	executionOrderId?: string
	globalId?: string
	height?: string
	localId: string
	targetName: string
	width?: string
}

export type Attributeslabel = {
	executionOrderId?: string
	globalId?: string
	height?: string
	label: string
	localId: string
	width?: string
}

export type Attributesld = {}

export type AttributesleftPowerRail = {
	executionOrderId?: string
	globalId?: string
	height?: string
	localId: string
	width?: string
}

export type AttributeslocalVars = {
	constant?: string
	name?: string
	nonpersistent?: string
	nonretain?: string
	persistent?: string
	retain?: string
}

export type AttributesmacroStep = {
	executionOrderId?: string
	globalId?: string
	height?: string
	localId: string
	name?: string
	width?: string
}

export type AttributesoutVariable = {
	edge?: 'none' | 'falling' | 'rising' | (string & {})
	executionOrderId?: string
	globalId?: string
	height?: string
	localId: string
	negated?: string
	storage?: 'none' | 'set' | 'reset' | (string & {})
	width?: string
}

export type AttributesoutputVariables = {}

export type AttributesoutputVars = {
	constant?: string
	name?: string
	nonpersistent?: string
	nonretain?: string
	persistent?: string
	retain?: string
}

export type AttributespageSize = {
	x: string
	y: string
}

export type Attributespointer = {}

export type Attributesposition = {
	x: string
	y: string
}

export type Attributespou = {
	globalId?: string
	name: string
	pouType: 'function' | 'functionBlock' | 'program' | (string & {})
}

export type AttributespouInstance = {
	globalId?: string
	name: string
	typeName: string
}

export type Attributespous = {}

export type Attributesproject = {}

export type Attributesrange = {
	lower: string
	upper: string
}

export type Attributesreference = {
	name: string
}

export type AttributesrelPosition = {
	x: string
	y: string
}

export type Attributesresource = {
	globalId?: string
	name: string
}

export type Attributesreturn = {
	executionOrderId?: string
	globalId?: string
	height?: string
	localId: string
	width?: string
}

export type AttributesreturnType = {}

export type AttributesrightPowerRail = {
	executionOrderId?: string
	globalId?: string
	height?: string
	localId: string
	width?: string
}

export type Attributesscaling = {
	x: string
	y: string
}

export type AttributesselectionConvergence = {
	globalId?: string
	height?: string
	localId: string
	width?: string
}

export type AttributesselectionDivergence = {
	globalId?: string
	height?: string
	localId: string
	width?: string
}

export type Attributessfc = {}

export type AttributessimpleValue = {
	value?: string
}

export type AttributessimultaneousConvergence = {
	globalId?: string
	height?: string
	localId: string
	width?: string
}

export type AttributessimultaneousDivergence = {
	globalId?: string
	height?: string
	localId: string
	name?: string
	width?: string
}

export type Attributesstep = {
	executionOrderId?: string
	globalId?: string
	height?: string
	initialStep?: string
	localId: string
	name: string
	negated?: string
	width?: string
}

export type Attributesstring = {
	length?: string
}

export type Attributesstruct = {
	constant?: string
	name?: string
	nonpersistent?: string
	nonretain?: string
	persistent?: string
	retain?: string
	'xsi:type'?: 'varList' | (string & {})
}

export type AttributesstructValue = {}

export type AttributessubrangeSigned = {}

export type AttributessubrangeUnsigned = {}

export type Attributestask = {
	globalId?: string
	interval?: string
	name: string
	priority: string
	single?: string
}

export type AttributestempVars = {
	constant?: string
	name?: string
	nonpersistent?: string
	nonretain?: string
	persistent?: string
	retain?: string
}

export type Attributestransition = {
	executionOrderId?: string
	globalId?: string
	height?: string
	localId: string
	priority?: string
	width?: string
}

export type Attributestransitions = {}

export type Attributestype = {}

export type Attributestypes = {}

export type Attributesvalue = {
	name: string
	value?: string
}

export type Attributesvalues = {}

export type Attributesvariable = {
	address?: string
	globalId?: string
	name: string
	'xsi:type'?: 'edgeModifierType' | 'storageModifierType' | (string & {})
}

export type AttributesvendorElement = {
	executionOrderId?: string
	globalId?: string
	height?: string
	localId: string
	width?: string
}

export type Attributeswstring = {
	length?: string
}

export type AttributesMap = {
	ANY: AttributesANY
	ANY_BIT: AttributesANY_BIT
	ANY_DATE: AttributesANY_DATE
	ANY_DERIVED: AttributesANY_DERIVED
	ANY_ELEMENTARY: AttributesANY_ELEMENTARY
	ANY_INT: AttributesANY_INT
	ANY_MAGNITUDE: AttributesANY_MAGNITUDE
	ANY_NUM: AttributesANY_NUM
	ANY_REAL: AttributesANY_REAL
	ANY_STRING: AttributesANY_STRING
	BOOL: AttributesBOOL
	BYTE: AttributesBYTE
	Comment: AttributesComment
	DATE: AttributesDATE
	DINT: AttributesDINT
	DT: AttributesDT
	DWORD: AttributesDWORD
	FBD: AttributesFBD
	IL: AttributesIL
	INT: AttributesINT
	LD: AttributesLD
	LINT: AttributesLINT
	LREAL: AttributesLREAL
	LWORD: AttributesLWORD
	REAL: AttributesREAL
	SFC: AttributesSFC
	SINT: AttributesSINT
	ST: AttributesST
	TIME: AttributesTIME
	TOD: AttributesTOD
	UDINT: AttributesUDINT
	UINT: AttributesUINT
	ULINT: AttributesULINT
	USINT: AttributesUSINT
	WORD: AttributesWORD
	accessVariable: AttributesaccessVariable
	accessVars: AttributesaccessVars
	action: Attributesaction
	actionBlock: AttributesactionBlock
	actions: Attributesactions
	addData: AttributesaddData
	addDataInfo: AttributesaddDataInfo
	alternativeText: AttributesalternativeText
	array: Attributesarray
	arrayValue: AttributesarrayValue
	baseType: AttributesbaseType
	block: Attributesblock
	body: Attributesbody
	coil: Attributescoil
	comment: Attributescomment
	condition: Attributescondition
	configVariable: AttributesconfigVariable
	configVars: AttributesconfigVars
	configuration: Attributesconfiguration
	configurations: Attributesconfigurations
	connection: Attributesconnection
	connectionPointIn: AttributesconnectionPointIn
	connectionPointOut: AttributesconnectionPointOut
	connectionPointOutAction: AttributesconnectionPointOutAction
	connector: Attributesconnector
	contact: Attributescontact
	content: Attributescontent
	contentHeader: AttributescontentHeader
	continuation: Attributescontinuation
	coordinateInfo: AttributescoordinateInfo
	data: Attributesdata
	dataType: AttributesdataType
	dataTypes: AttributesdataTypes
	derived: Attributesderived
	description: Attributesdescription
	dimension: Attributesdimension
	documentation: Attributesdocumentation
	enum: Attributesenum
	error: Attributeserror
	expression: Attributesexpression
	externalVars: AttributesexternalVars
	fbd: Attributesfbd
	fileHeader: AttributesfileHeader
	globalVars: AttributesglobalVars
	inOutVariable: AttributesinOutVariable
	inOutVariables: AttributesinOutVariables
	inOutVars: AttributesinOutVars
	inVariable: AttributesinVariable
	info: Attributesinfo
	initialValue: AttributesinitialValue
	inline: Attributesinline
	inputVariables: AttributesinputVariables
	inputVars: AttributesinputVars
	instances: Attributesinstances
	interface: Attributesinterface
	jump: Attributesjump
	jumpStep: AttributesjumpStep
	label: Attributeslabel
	ld: Attributesld
	leftPowerRail: AttributesleftPowerRail
	localVars: AttributeslocalVars
	macroStep: AttributesmacroStep
	outVariable: AttributesoutVariable
	outputVariables: AttributesoutputVariables
	outputVars: AttributesoutputVars
	pageSize: AttributespageSize
	pointer: Attributespointer
	position: Attributesposition
	pou: Attributespou
	pouInstance: AttributespouInstance
	pous: Attributespous
	project: Attributesproject
	range: Attributesrange
	reference: Attributesreference
	relPosition: AttributesrelPosition
	resource: Attributesresource
	return: Attributesreturn
	returnType: AttributesreturnType
	rightPowerRail: AttributesrightPowerRail
	scaling: Attributesscaling
	selectionConvergence: AttributesselectionConvergence
	selectionDivergence: AttributesselectionDivergence
	sfc: Attributessfc
	simpleValue: AttributessimpleValue
	simultaneousConvergence: AttributessimultaneousConvergence
	simultaneousDivergence: AttributessimultaneousDivergence
	step: Attributesstep
	string: Attributesstring
	struct: Attributesstruct
	structValue: AttributesstructValue
	subrangeSigned: AttributessubrangeSigned
	subrangeUnsigned: AttributessubrangeUnsigned
	task: Attributestask
	tempVars: AttributestempVars
	transition: Attributestransition
	transitions: Attributestransitions
	type: Attributestype
	types: Attributestypes
	value: Attributesvalue
	values: Attributesvalues
	variable: Attributesvariable
	vendorElement: AttributesvendorElement
	wstring: Attributeswstring
}

export type AttributesOf<T extends AvailableElement> = AttributesMap[T]

export type RequiredAttributeNames<T extends AvailableElement> =
	(typeof REQUIRED_ATTRIBUTES)[T][number]
export type OptionalAttributeNames<T extends AvailableElement> = Exclude<
	keyof AttributesOf<T>,
	RequiredAttributeNames<T>
>
