// Auto-generated by generate.py — do not edit

import type { ELEMENT_NAMES, REQUIRED_ATTRIBUTES } from './constants.generated'

export type AvailableElement = (typeof ELEMENT_NAMES)[number]

export type AttributesAccessVariable = {
	alias: string
	direction?: 'readOnly' | 'readWrite' | (string & {})
	globalId?: string
	instancePathAndName: string
	pragma?: string
}

export type AttributesAccessVars = {
	accessSpecifier?: 'private' | 'protected' | 'internal' | 'public' | (string & {})
	constant?: string
	globalId?: string
	non_retain?: string
	pragma?: string
	retain?: string
	'xsi:type'?: 'VarListWithAccessSpec' | (string & {})
}

export type AttributesAccessVarsInConfiguration = {
	globalId?: string
	pragma?: string
}

export type AttributesAccessVarsInProgram = {
	constant?: string
	globalId?: string
	non_retain?: string
	pragma?: string
	retain?: string
}

export type AttributesAction = {
	globalId?: string
	name: string
	pragma?: string
}

export type AttributesActionBlock = {
	globalId?: string
	indicator?: string
}

export type AttributesActionQualifier = {
	duration?: string
	qualifier?:
		| 'P1'
		| 'N'
		| 'P0'
		| 'R'
		| 'S'
		| 'L'
		| 'D'
		| 'P'
		| 'DS'
		| 'DL'
		| 'SD'
		| 'SL'
		| (string & {})
}

export type AttributesAddData = {}

export type AttributesAddDataInfo = {}

export type AttributesAddress = {
	address?: string
	globalId?: string
	location?: 'I' | 'Q' | 'M' | (string & {})
	notYetFixed?: string
	pragma?: string
	size?: 'X' | 'B' | 'W' | 'D' | 'L' | (string & {})
	'xsi:type'?: 'AddressExpression' | (string & {})
}

export type AttributesAddressInConfigVariable = {
	address?: string
	globalId?: string
	location?: 'I' | 'Q' | 'M' | (string & {})
	pragma?: string
	size?: 'X' | 'B' | 'W' | 'D' | 'L' | (string & {})
}

export type AttributesAddressInMember = {
	address?: string
	globalId?: string
	location?: 'I' | 'Q' | 'M' | (string & {})
	notYetFixed?: string
	pragma?: string
	size?: 'X' | 'B' | 'W' | 'D' | 'L' | (string & {})
}

export type AttributesAddressInVariable = {
	address?: string
	globalId?: string
	location?: 'I' | 'Q' | 'M' | (string & {})
	notYetFixed?: string
	pragma?: string
	size?: 'X' | 'B' | 'W' | 'D' | 'L' | (string & {})
}

export type AttributesArrayValue = {}

export type AttributesBaseType = {}

export type AttributesBaseTypeInInstantlyDefinedType = {}

export type AttributesBaseTypeInUserDefinedTypeSpec = {}

export type AttributesBody = {
	globalId?: string
	pragma?: string
}

export type AttributesBodyInAction = {
	globalId?: string
	pragma?: string
}

export type AttributesBodyInMethod = {
	globalId?: string
	pragma?: string
}

export type AttributesBodyContent = {
	'xsi:type'?: 'FBD' | 'IL' | 'LD' | 'SFC' | 'ST' | (string & {})
}

export type AttributesBodyContentInBody = {}

export type AttributesBodyContentInInline = {}

export type AttributesBodyContentInMainBody = {}

export type AttributesClass = {
	abstract?: string
	final?: string
	globalId?: string
	internal?: string
	name: string
	pragma?: string
}

export type AttributesCommonObject = {
	globalId?: string
	label?: string
	'xsi:type'?: 'ActionBlocks' | 'Comment' | 'Connector' | 'Continuation' | (string & {})
}

export type AttributesComplexOperand = {
	'xsi:type'?: 'AccessSpecifiers' | 'EdgeModifierType' | (string & {})
}

export type AttributesCondition = {
	globalId?: string
	pragma?: string
}

export type AttributesConditionInSfcObject = {}

export type AttributesConditionInTransition = {
	globalId?: string
	pragma?: string
}

export type AttributesConfigVariable = {
	globalId?: string
	instancePathAndName: string
	pragma?: string
}

export type AttributesConfigVars = {
	globalId?: string
	pragma?: string
}

export type AttributesConfiguration = {
	globalId?: string
	name: string
	pragma?: string
}

export type AttributesConnection = {
	feedbackVariable?: string
	globalId?: string
	refConnectionPointOutId: string
	'xsi:type'?: 'FeedbackConnection' | (string & {})
}

export type AttributesConnectionPointIn = {
	globalId?: string
}

export type AttributesConnectionPointOut = {
	connectionPointOutId: string
	globalId?: string
	priority?: string
}

export type AttributesConnectionPointOutInCommonObject = {
	connectionPointOutId: string
	globalId?: string
}

export type AttributesConnectionPointOutInFbdObject = {
	connectionPointOutId: string
	globalId?: string
}

export type AttributesConnectionPointOutInInOutVariable = {
	connectionPointOutId: string
	globalId?: string
}

export type AttributesConnectionPointOutInLdObject = {
	connectionPointOutId: string
	globalId?: string
}

export type AttributesConnectionPointOutInOutputVariable = {
	connectionPointOutId: string
	globalId?: string
}

export type AttributesConnectionPointOutInSfcObject = {
	connectionPointOutId: string
	globalId?: string
}

export type AttributesConnectionPointOutAction = {
	connectionPointOutId: string
	globalId?: string
}

export type AttributesContent = {
	'xsi:type'?: 'SimpleText' | (string & {})
}

export type AttributesContentHeader = {
	author?: string
	creationDateTime: string
	language?: string
	modificationDateTime?: string
	name: string
	organization?: string
	version?: string
}

export type AttributesCoordinateInfo = {}

export type AttributesData = {
	handleUnknown: 'preserve' | 'discard' | 'implementation' | (string & {})
	name: string
}

export type AttributesDataTypeDecl = {
	globalId?: string
	internal?: string
	name: string
	pragma?: string
}

export type AttributesDescription = {
	'xsi:type'?: 'SimpleText' | (string & {})
}

export type AttributesDimensionSpec = {
	dimensionNumber: string
}

export type AttributesDocumentation = {
	'xsi:type'?: 'SimpleText' | (string & {})
}

export type AttributesEnumerator = {
	name: string
	value?: string
}

export type AttributesEnumeratorInUserDefinedTypeSpec = {
	name: string
	value: string
}

export type AttributesExtends = {}

export type AttributesExternalVars = {
	constant?: string
	globalId?: string
	pragma?: string
}

export type AttributesFbInstTaskAssociation = {
	associatedTaskName: string
	fbInstanceName: string
}

export type AttributesFbdObject = {
	complexIdentifier?: string
	globalId?: string
	identifier?: string
	instanceName?: string
	targetNetworkLabel?: string
	typeName?: string
	'xsi:type'?:
		| 'Block'
		| 'DataSink'
		| 'DataSource'
		| 'Jump'
		| 'Return'
		| 'Unconnected'
		| (string & {})
}

export type AttributesFbdScaling = {
	x: string
	y: string
}

export type AttributesFeedbackConnection = {
	feedbackVariable: string
	globalId?: string
	refConnectionPointOutId: string
}

export type AttributesFileHeader = {
	companyName: string
	companyURL?: string
	productName: string
	productRelease?: string
	productVersion: string
}

export type AttributesFunction = {
	globalId?: string
	internal?: string
	name: string
	pragma?: string
}

export type AttributesFunctionBlock = {
	abstract?: string
	final?: string
	globalId?: string
	internal?: string
	name: string
	pragma?: string
}

export type AttributesGlobalNamespace = {
	globalId?: string
	pragma?: string
}

export type AttributesGlobalVars = {
	accessSpecifier?: 'private' | 'protected' | 'internal' | 'public' | (string & {})
	constant?: string
	globalId?: string
	non_retain?: string
	pragma?: string
	retain?: string
	'xsi:type'?: 'VarListWithAccessSpec' | (string & {})
}

export type AttributesGraphicalExpression = {
	evaluationOrder: string
	globalId?: string
	label?: string
	'xsi:type'?: 'FbdNetwork' | 'LadderRung' | (string & {})
}

export type AttributesGraphicalPredicate = {}

export type AttributesIL = {
	'xsi:type'?: 'AccessSpecifiers' | 'EdgeModifierType' | (string & {})
}

export type AttributesImplements = {}

export type AttributesInOutAssignment = {
	actualValue: string
	formalParameter: string
}

export type AttributesInOutVariable = {
	globalId?: string
	negated?: string
	parameterName: string
}

export type AttributesInOutVariables = {}

export type AttributesIndexRange = {
	lower: string
	upper: string
}

export type AttributesInfo = {
	name: string
	vendor: string
	version?: string
}

export type AttributesInitialValue = {
	'xsi:type'?: 'AccessSpecifiers' | 'EdgeModifierType' | (string & {})
}

export type AttributesInitialValueInConfigVariable = {}

export type AttributesInitialValueInMember = {}

export type AttributesInitialValueInUserDefinedTypeSpec = {}

export type AttributesInitialValueInVariable = {}

export type AttributesInline = {
	globalId?: string
	pragma?: string
}

export type AttributesInoutVars = {}

export type AttributesInputAssignment = {
	actualValue: string
	formalParameter: string
}

export type AttributesInputVariable = {
	edge?: 'none' | 'falling' | 'rising' | (string & {})
	globalId?: string
	negated?: string
	parameterName: string
	suppressName?: string
}

export type AttributesInputVariables = {}

export type AttributesInputVars = {
	non_retain?: string
	retain?: string
}

export type AttributesInstances = {}

export type AttributesInstantlyDefinedType = {
	'xsi:type'?: 'ArrayTypeSpec' | 'ReferenceTypeSpec' | (string & {})
}

export type AttributesInterface = {
	globalId?: string
	internal?: string
	name: string
	pragma?: string
}

export type AttributesLdObject = {
	compareOperator?: '>' | '>=' | '=' | '<=' | '<' | '<>' | (string & {})
	edge?: 'none' | 'falling' | 'rising' | (string & {})
	globalId?: string
	latch?: 'none' | 'set' | 'reset' | (string & {})
	negated?: string
	operand?: string
	operand1?: string
	operand2?: string
	'xsi:type'?:
		| 'Coil'
		| 'CompareContact'
		| 'Contact'
		| 'LeftPowerRail'
		| 'RightPowerRail'
		| (string & {})
}

export type AttributesLdScaling = {
	x: string
	y: string
}

export type AttributesMainBody = {
	globalId?: string
	pragma?: string
}

export type AttributesMainBodyInFunction = {
	globalId?: string
	pragma?: string
}

export type AttributesMainBodyInFunctionBlock = {
	globalId?: string
	pragma?: string
}

export type AttributesMainBodyInProgram = {
	globalId?: string
	pragma?: string
}

export type AttributesMember = {
	globalId?: string
	name: string
	pragma?: string
}

export type AttributesMethod = {
	abstract?: string
	accessSpecifier?: 'private' | 'protected' | 'internal' | 'public' | (string & {})
	final?: string
	globalId?: string
	name: string
	override?: string
	pragma?: string
}

export type AttributesMethodInClass = {
	abstract?: string
	accessSpecifier: 'private' | 'protected' | 'internal' | 'public' | (string & {})
	final?: string
	globalId?: string
	name: string
	override?: string
	pragma?: string
}

export type AttributesMethodInFunctionBlock = {
	abstract?: string
	accessSpecifier: 'private' | 'protected' | 'internal' | 'public' | (string & {})
	final?: string
	globalId?: string
	name: string
	override?: string
	pragma?: string
}

export type AttributesMethodInInterface = {
	globalId?: string
	name: string
	pragma?: string
}

export type AttributesNamespaceDecl = {
	globalId?: string
	internal?: string
	name: string
	pragma?: string
}

export type AttributesNetwork = {
	evaluationOrder: string
	globalId?: string
	label?: string
}

export type AttributesOutputAssignment = {
	actualValue: string
	formalParameter: string
}

export type AttributesOutputVariable = {
	globalId?: string
	negated?: string
	parameterName: string
	suppressName?: string
}

export type AttributesOutputVariables = {}

export type AttributesOutputVars = {
	non_retain?: string
	retain?: string
}

export type AttributesParameters = {}

export type AttributesPredicateContent = {
	'xsi:type'?: 'FBD' | 'IL' | 'LD' | 'ST' | (string & {})
}

export type AttributesProgram = {
	globalId?: string
	internal?: string
	name: string
	pragma?: string
}

export type AttributesProgramInstance = {
	associatedTaskName?: string
	evaluationOrder?: string
	globalId?: string
	name: string
	pragma?: string
	typeName: string
}

export type AttributesProject = {
	schemaVersion: string
}

export type AttributesRange = {
	lower: string
	upper: string
}

export type AttributesReference = {
	name: string
}

export type AttributesReferenceName = {
	'xsi:type'?: 'AccessSpecifiers' | 'EdgeModifierType' | (string & {})
}

export type AttributesReferenceTo = {}

export type AttributesRelPosition = {
	x: string
	y: string
}

export type AttributesResource = {
	globalId?: string
	name: string
	pragma?: string
	resourceTypeName: string
}

export type AttributesResultType = {}

export type AttributesRung = {
	evaluationOrder: string
	globalId?: string
	label?: string
}

export type AttributesST = {
	'xsi:type'?: 'AccessSpecifiers' | 'EdgeModifierType' | (string & {})
}

export type AttributesSfcObject = {
	globalId?: string
	initialStep?: string
	mutualExclusion?: string
	name?: string
	'xsi:type'?:
		| 'SelectionConvergence'
		| 'SelectionDivergence'
		| 'SimultaneousConvergence'
		| 'SimultaneousDivergence'
		| 'Step'
		| 'Transition'
		| (string & {})
}

export type AttributesSfcScaling = {
	x: string
	y: string
}

export type AttributesSimpleValue = {
	value?: string
}

export type AttributesSize = {
	x: string
	y: string
}

export type AttributesStructValue = {}

export type AttributesTask = {
	globalId?: string
	interval?: string
	name: string
	pragma?: string
	priority?: string
	single?: string
	'xsi:type'?: 'StandardTask' | (string & {})
}

export type AttributesTempVars = {
	accessSpecifier?: 'private' | 'protected' | 'internal' | 'public' | (string & {})
	constant?: string
	globalId?: string
	non_retain?: string
	pragma?: string
	retain?: string
	'xsi:type'?: 'VarListWithAccessSpec' | (string & {})
}

export type AttributesTextualPredicate = {
	globalId?: string
	pragma?: string
}

export type AttributesTransition = {
	globalId?: string
	name: string
	pragma?: string
}

export type AttributesType = {}

export type AttributesTypeInAccessVariable = {}

export type AttributesTypeInConfigVariable = {}

export type AttributesTypeInLdObject = {}

export type AttributesTypeInMember = {}

export type AttributesTypeInVariable = {}

export type AttributesTypeName = {
	'xsi:type'?: 'AccessSpecifiers' | 'EdgeModifierType' | (string & {})
}

export type AttributesTypes = {}

export type AttributesUserDefinedTypeSpec = {
	overlap?: string
	'xsi:type'?:
		| 'ArrayTypeSpec'
		| 'DirectlyDerivedTypeSpec'
		| 'EnumTypeSpec'
		| 'EnumTypeWithNamedValueSpec'
		| 'ReferenceTypeSpec'
		| 'StructTypeSpec'
		| 'SubrangeTypeSpec'
		| (string & {})
}

export type AttributesUsingDirective = {
	'xsi:type'?: 'AccessSpecifiers' | 'EdgeModifierType' | (string & {})
}

export type AttributesValue = {
	repetitionValue?: string
	member?: string
}

export type AttributesValueInArrayValue = {
	repetitionValue?: string
}

export type AttributesValueInStructValue = {
	member: string
}

export type AttributesVariable = {
	edgeDetection?: 'none' | 'falling' | 'rising' | (string & {})
	globalId?: string
	name: string
	orderWithinParamSet?: string
	pragma?: string
	'xsi:type'?: 'VariableDecl' | (string & {})
}

export type AttributesVariableInAccessVars = {
	globalId?: string
	name: string
	pragma?: string
}

export type AttributesVariableInExternalVars = {
	globalId?: string
	name: string
	pragma?: string
}

export type AttributesVariableInGlobalVars = {
	globalId?: string
	name: string
	pragma?: string
}

export type AttributesVariableInInoutVars = {
	globalId?: string
	name: string
	orderWithinParamSet: string
	pragma?: string
}

export type AttributesVariableInInputVars = {
	edgeDetection?: 'none' | 'falling' | 'rising' | (string & {})
	globalId?: string
	name: string
	orderWithinParamSet: string
	pragma?: string
}

export type AttributesVariableInOutputVars = {
	globalId?: string
	name: string
	orderWithinParamSet: string
	pragma?: string
}

export type AttributesVariableInTempVars = {
	globalId?: string
	name: string
	pragma?: string
}

export type AttributesVariableInVars = {
	globalId?: string
	name: string
	pragma?: string
}

export type AttributesVariableLength = {}

export type AttributesVars = {
	accessSpecifier: 'private' | 'protected' | 'internal' | 'public' | (string & {})
	constant?: string
	globalId?: string
	non_retain?: string
	pragma?: string
	retain?: string
}

export type AttributesMap = {
	AccessVariable: AttributesAccessVariable
	AccessVars: AttributesAccessVars
	Action: AttributesAction
	ActionBlock: AttributesActionBlock
	ActionQualifier: AttributesActionQualifier
	AddData: AttributesAddData
	AddDataInfo: AttributesAddDataInfo
	Address: AttributesAddress
	ArrayValue: AttributesArrayValue
	BaseType: AttributesBaseType
	Body: AttributesBody
	BodyContent: AttributesBodyContent
	Class: AttributesClass
	CommonObject: AttributesCommonObject
	ComplexOperand: AttributesComplexOperand
	Condition: AttributesCondition
	ConfigVariable: AttributesConfigVariable
	ConfigVars: AttributesConfigVars
	Configuration: AttributesConfiguration
	Connection: AttributesConnection
	ConnectionPointIn: AttributesConnectionPointIn
	ConnectionPointOut: AttributesConnectionPointOut
	ConnectionPointOutAction: AttributesConnectionPointOutAction
	Content: AttributesContent
	ContentHeader: AttributesContentHeader
	CoordinateInfo: AttributesCoordinateInfo
	Data: AttributesData
	DataTypeDecl: AttributesDataTypeDecl
	Description: AttributesDescription
	DimensionSpec: AttributesDimensionSpec
	Documentation: AttributesDocumentation
	Enumerator: AttributesEnumerator
	Extends: AttributesExtends
	ExternalVars: AttributesExternalVars
	FbInstTaskAssociation: AttributesFbInstTaskAssociation
	FbdObject: AttributesFbdObject
	FbdScaling: AttributesFbdScaling
	FeedbackConnection: AttributesFeedbackConnection
	FileHeader: AttributesFileHeader
	Function: AttributesFunction
	FunctionBlock: AttributesFunctionBlock
	GlobalNamespace: AttributesGlobalNamespace
	GlobalVars: AttributesGlobalVars
	GraphicalExpression: AttributesGraphicalExpression
	GraphicalPredicate: AttributesGraphicalPredicate
	IL: AttributesIL
	Implements: AttributesImplements
	InOutAssignment: AttributesInOutAssignment
	InOutVariable: AttributesInOutVariable
	InOutVariables: AttributesInOutVariables
	IndexRange: AttributesIndexRange
	Info: AttributesInfo
	InitialValue: AttributesInitialValue
	Inline: AttributesInline
	InoutVars: AttributesInoutVars
	InputAssignment: AttributesInputAssignment
	InputVariable: AttributesInputVariable
	InputVariables: AttributesInputVariables
	InputVars: AttributesInputVars
	Instances: AttributesInstances
	InstantlyDefinedType: AttributesInstantlyDefinedType
	Interface: AttributesInterface
	LdObject: AttributesLdObject
	LdScaling: AttributesLdScaling
	MainBody: AttributesMainBody
	Member: AttributesMember
	Method: AttributesMethod
	NamespaceDecl: AttributesNamespaceDecl
	Network: AttributesNetwork
	OutputAssignment: AttributesOutputAssignment
	OutputVariable: AttributesOutputVariable
	OutputVariables: AttributesOutputVariables
	OutputVars: AttributesOutputVars
	Parameters: AttributesParameters
	PredicateContent: AttributesPredicateContent
	Program: AttributesProgram
	ProgramInstance: AttributesProgramInstance
	Project: AttributesProject
	Range: AttributesRange
	Reference: AttributesReference
	ReferenceName: AttributesReferenceName
	ReferenceTo: AttributesReferenceTo
	RelPosition: AttributesRelPosition
	Resource: AttributesResource
	ResultType: AttributesResultType
	Rung: AttributesRung
	ST: AttributesST
	SfcObject: AttributesSfcObject
	SfcScaling: AttributesSfcScaling
	SimpleValue: AttributesSimpleValue
	Size: AttributesSize
	StructValue: AttributesStructValue
	Task: AttributesTask
	TempVars: AttributesTempVars
	TextualPredicate: AttributesTextualPredicate
	Transition: AttributesTransition
	Type: AttributesType
	TypeName: AttributesTypeName
	Types: AttributesTypes
	UserDefinedTypeSpec: AttributesUserDefinedTypeSpec
	UsingDirective: AttributesUsingDirective
	Value: AttributesValue
	Variable: AttributesVariable
	VariableLength: AttributesVariableLength
	Vars: AttributesVars
}

export type AttributesOf<T extends AvailableElement> = AttributesMap[T]

/**
 * The attributes of a child AS DECLARED UNDER each parent. An element declared once has the
 * same type under every parent; a homonym has the type of its declaration under each. Read
 * through the dialecte's `AttributesOf<Element, Parent>`; the constant `ATTRIBUTES.byParent`
 * is checked against this map.
 */
export type AttributesByParent = {
	AccessVariable: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		UsingDirective: AttributesUsingDirective
		Type: AttributesTypeInAccessVariable
	}
	AccessVars: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		UsingDirective: AttributesUsingDirective
		Variable: AttributesVariableInAccessVars
		AccessVariable: AttributesAccessVariable
	}
	Action: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		UsingDirective: AttributesUsingDirective
		Body: AttributesBodyInAction
	}
	ActionBlock: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		RelPosition: AttributesRelPosition
		Size: AttributesSize
		ActionQualifier: AttributesActionQualifier
		Inline: AttributesInline
		ComplexOperand: AttributesComplexOperand
		ReferenceName: AttributesReferenceName
	}
	AddData: {
		Data: AttributesData
	}
	AddDataInfo: {
		Info: AttributesInfo
	}
	Address: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		UsingDirective: AttributesUsingDirective
	}
	ArrayValue: {
		Value: AttributesValueInArrayValue
	}
	BaseType: {
		TypeName: AttributesTypeName
		InstantlyDefinedType: AttributesInstantlyDefinedType
	}
	Body: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		UsingDirective: AttributesUsingDirective
		BodyContent: AttributesBodyContentInBody
	}
	BodyContent: {
		Network: AttributesNetwork
		IL: AttributesIL
		Rung: AttributesRung
		CommonObject: AttributesCommonObject
		LdObject: AttributesLdObject
		FbdObject: AttributesFbdObject
		SfcObject: AttributesSfcObject
		ST: AttributesST
	}
	Class: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		UsingDirective: AttributesUsingDirective
		Extends: AttributesExtends
		Implements: AttributesImplements
		ExternalVars: AttributesExternalVars
		Vars: AttributesVars
		Method: AttributesMethodInClass
	}
	CommonObject: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		RelPosition: AttributesRelPosition
		Size: AttributesSize
		ConnectionPointIn: AttributesConnectionPointIn
		ActionBlock: AttributesActionBlock
		Content: AttributesContent
		ConnectionPointOut: AttributesConnectionPointOutInCommonObject
	}
	Condition: {
		Reference: AttributesReference
		GraphicalPredicate: AttributesGraphicalPredicate
		TextualPredicate: AttributesTextualPredicate
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		UsingDirective: AttributesUsingDirective
		PredicateContent: AttributesPredicateContent
	}
	ConfigVariable: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		UsingDirective: AttributesUsingDirective
		Type: AttributesTypeInConfigVariable
		InitialValue: AttributesInitialValueInConfigVariable
		Address: AttributesAddressInConfigVariable
	}
	ConfigVars: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		UsingDirective: AttributesUsingDirective
		ConfigVariable: AttributesConfigVariable
	}
	Configuration: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		UsingDirective: AttributesUsingDirective
		Resource: AttributesResource
		GlobalVars: AttributesGlobalVars
		AccessVars: AttributesAccessVarsInConfiguration
		ConfigVars: AttributesConfigVars
	}
	Connection: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		RelPosition: AttributesRelPosition
	}
	ConnectionPointIn: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		RelPosition: AttributesRelPosition
		Connection: AttributesConnection
		FeedbackConnection: AttributesFeedbackConnection
	}
	ConnectionPointOut: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		RelPosition: AttributesRelPosition
	}
	ConnectionPointOutAction: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		RelPosition: AttributesRelPosition
	}
	ContentHeader: {
		CoordinateInfo: AttributesCoordinateInfo
		AddDataInfo: AttributesAddDataInfo
		AddData: AttributesAddData
	}
	CoordinateInfo: {
		FbdScaling: AttributesFbdScaling
		LdScaling: AttributesLdScaling
		SfcScaling: AttributesSfcScaling
	}
	DataTypeDecl: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		UsingDirective: AttributesUsingDirective
		UserDefinedTypeSpec: AttributesUserDefinedTypeSpec
	}
	DimensionSpec: {
		IndexRange: AttributesIndexRange
		VariableLength: AttributesVariableLength
	}
	Enumerator: {
		Documentation: AttributesDocumentation
	}
	Extends: {
		TypeName: AttributesTypeName
		InstantlyDefinedType: AttributesInstantlyDefinedType
	}
	ExternalVars: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		UsingDirective: AttributesUsingDirective
		Variable: AttributesVariableInExternalVars
	}
	FbdObject: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		RelPosition: AttributesRelPosition
		Size: AttributesSize
		InOutVariables: AttributesInOutVariables
		InputVariables: AttributesInputVariables
		OutputVariables: AttributesOutputVariables
		ConnectionPointIn: AttributesConnectionPointIn
		ConnectionPointOut: AttributesConnectionPointOutInFbdObject
	}
	FeedbackConnection: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		RelPosition: AttributesRelPosition
	}
	FileHeader: {
		AddData: AttributesAddData
	}
	Function: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		UsingDirective: AttributesUsingDirective
		ResultType: AttributesResultType
		Parameters: AttributesParameters
		ExternalVars: AttributesExternalVars
		TempVars: AttributesTempVars
		MainBody: AttributesMainBodyInFunction
	}
	FunctionBlock: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		UsingDirective: AttributesUsingDirective
		Extends: AttributesExtends
		Implements: AttributesImplements
		Parameters: AttributesParameters
		ExternalVars: AttributesExternalVars
		Vars: AttributesVars
		TempVars: AttributesTempVars
		Method: AttributesMethodInFunctionBlock
		MainBody: AttributesMainBodyInFunctionBlock
		Action: AttributesAction
		Transition: AttributesTransition
	}
	GlobalNamespace: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		UsingDirective: AttributesUsingDirective
		NamespaceDecl: AttributesNamespaceDecl
		DataTypeDecl: AttributesDataTypeDecl
		Program: AttributesProgram
		FunctionBlock: AttributesFunctionBlock
		Class: AttributesClass
		Function: AttributesFunction
		Interface: AttributesInterface
	}
	GlobalVars: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		UsingDirective: AttributesUsingDirective
		Variable: AttributesVariableInGlobalVars
	}
	GraphicalExpression: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		RelPosition: AttributesRelPosition
		Size: AttributesSize
		CommonObject: AttributesCommonObject
		FbdObject: AttributesFbdObject
		LdObject: AttributesLdObject
	}
	GraphicalPredicate: {
		ConnectionPointIn: AttributesConnectionPointIn
		GraphicalExpression: AttributesGraphicalExpression
	}
	Implements: {
		TypeName: AttributesTypeName
		InstantlyDefinedType: AttributesInstantlyDefinedType
	}
	InOutVariable: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		ConnectionPointIn: AttributesConnectionPointIn
		ConnectionPointOut: AttributesConnectionPointOutInInOutVariable
	}
	InOutVariables: {
		InOutVariable: AttributesInOutVariable
	}
	Info: {
		Description: AttributesDescription
	}
	InitialValue: {
		SimpleValue: AttributesSimpleValue
		ArrayValue: AttributesArrayValue
		StructValue: AttributesStructValue
	}
	Inline: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		UsingDirective: AttributesUsingDirective
		BodyContent: AttributesBodyContentInInline
	}
	InoutVars: {
		Variable: AttributesVariableInInoutVars
	}
	InputVariable: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		ConnectionPointIn: AttributesConnectionPointIn
	}
	InputVariables: {
		InputVariable: AttributesInputVariable
	}
	InputVars: {
		Variable: AttributesVariableInInputVars
	}
	Instances: {
		Configuration: AttributesConfiguration
	}
	InstantlyDefinedType: {
		BaseType: AttributesBaseTypeInInstantlyDefinedType
		DimensionSpec: AttributesDimensionSpec
		AddData: AttributesAddData
		ReferenceTo: AttributesReferenceTo
	}
	Interface: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		UsingDirective: AttributesUsingDirective
		Extends: AttributesExtends
		Method: AttributesMethodInInterface
	}
	LdObject: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		RelPosition: AttributesRelPosition
		Size: AttributesSize
		ConnectionPointIn: AttributesConnectionPointIn
		ConnectionPointOut: AttributesConnectionPointOutInLdObject
		Type: AttributesTypeInLdObject
	}
	MainBody: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		UsingDirective: AttributesUsingDirective
		BodyContent: AttributesBodyContentInMainBody
	}
	Member: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		UsingDirective: AttributesUsingDirective
		Type: AttributesTypeInMember
		InitialValue: AttributesInitialValueInMember
		Address: AttributesAddressInMember
	}
	Method: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		UsingDirective: AttributesUsingDirective
		ResultType: AttributesResultType
		Parameters: AttributesParameters
		TempVars: AttributesTempVars
		Body: AttributesBodyInMethod
	}
	NamespaceDecl: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		UsingDirective: AttributesUsingDirective
		NamespaceDecl: AttributesNamespaceDecl
		DataTypeDecl: AttributesDataTypeDecl
		Program: AttributesProgram
		FunctionBlock: AttributesFunctionBlock
		Class: AttributesClass
		Function: AttributesFunction
		Interface: AttributesInterface
	}
	Network: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		RelPosition: AttributesRelPosition
		Size: AttributesSize
		CommonObject: AttributesCommonObject
		FbdObject: AttributesFbdObject
	}
	OutputVariable: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		ConnectionPointOut: AttributesConnectionPointOutInOutputVariable
	}
	OutputVariables: {
		OutputVariable: AttributesOutputVariable
	}
	OutputVars: {
		Variable: AttributesVariableInOutputVars
	}
	Parameters: {
		InoutVars: AttributesInoutVars
		InputVars: AttributesInputVars
		OutputVars: AttributesOutputVars
	}
	PredicateContent: {
		Network: AttributesNetwork
		IL: AttributesIL
		Rung: AttributesRung
		ST: AttributesST
	}
	Program: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		UsingDirective: AttributesUsingDirective
		AccessVars: AttributesAccessVarsInProgram
		GlobalVars: AttributesGlobalVars
		Parameters: AttributesParameters
		ExternalVars: AttributesExternalVars
		Vars: AttributesVars
		TempVars: AttributesTempVars
		MainBody: AttributesMainBodyInProgram
		Action: AttributesAction
		Transition: AttributesTransition
	}
	ProgramInstance: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		UsingDirective: AttributesUsingDirective
		InputAssignment: AttributesInputAssignment
		OutputAssignment: AttributesOutputAssignment
		InOutAssignment: AttributesInOutAssignment
		FbInstTaskAssociation: AttributesFbInstTaskAssociation
	}
	Project: {
		FileHeader: AttributesFileHeader
		ContentHeader: AttributesContentHeader
		Types: AttributesTypes
		Instances: AttributesInstances
		AddData: AttributesAddData
		Documentation: AttributesDocumentation
	}
	ReferenceTo: {
		TypeName: AttributesTypeName
		InstantlyDefinedType: AttributesInstantlyDefinedType
	}
	Resource: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		UsingDirective: AttributesUsingDirective
		GlobalVars: AttributesGlobalVars
		Task: AttributesTask
		ProgramInstance: AttributesProgramInstance
	}
	ResultType: {
		TypeName: AttributesTypeName
		InstantlyDefinedType: AttributesInstantlyDefinedType
	}
	Rung: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		RelPosition: AttributesRelPosition
		Size: AttributesSize
		CommonObject: AttributesCommonObject
		LdObject: AttributesLdObject
		FbdObject: AttributesFbdObject
	}
	SfcObject: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		RelPosition: AttributesRelPosition
		Size: AttributesSize
		ConnectionPointIn: AttributesConnectionPointIn
		ConnectionPointOut: AttributesConnectionPointOutInSfcObject
		ConnectionPointOutAction: AttributesConnectionPointOutAction
		Condition: AttributesConditionInSfcObject
	}
	StructValue: {
		Value: AttributesValueInStructValue
	}
	Task: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		UsingDirective: AttributesUsingDirective
	}
	TempVars: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		UsingDirective: AttributesUsingDirective
		Variable: AttributesVariableInTempVars
	}
	TextualPredicate: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		UsingDirective: AttributesUsingDirective
		PredicateContent: AttributesPredicateContent
	}
	Transition: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		UsingDirective: AttributesUsingDirective
		Condition: AttributesConditionInTransition
	}
	Type: {
		TypeName: AttributesTypeName
		InstantlyDefinedType: AttributesInstantlyDefinedType
	}
	Types: {
		GlobalNamespace: AttributesGlobalNamespace
	}
	UserDefinedTypeSpec: {
		BaseType: AttributesBaseTypeInUserDefinedTypeSpec
		DimensionSpec: AttributesDimensionSpec
		AddData: AttributesAddData
		InitialValue: AttributesInitialValueInUserDefinedTypeSpec
		Enumerator: AttributesEnumeratorInUserDefinedTypeSpec
		ReferenceTo: AttributesReferenceTo
		Member: AttributesMember
		Range: AttributesRange
	}
	Value: {
		SimpleValue: AttributesSimpleValue
		ArrayValue: AttributesArrayValue
		StructValue: AttributesStructValue
	}
	Variable: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		UsingDirective: AttributesUsingDirective
		Type: AttributesTypeInVariable
		InitialValue: AttributesInitialValueInVariable
		Address: AttributesAddressInVariable
	}
	Vars: {
		Documentation: AttributesDocumentation
		AddData: AttributesAddData
		UsingDirective: AttributesUsingDirective
		Variable: AttributesVariableInVars
	}
}

export type RequiredAttributeNames<T extends AvailableElement> =
	(typeof REQUIRED_ATTRIBUTES)[T][number]
export type OptionalAttributeNames<T extends AvailableElement> = Exclude<
	keyof AttributesOf<T>,
	RequiredAttributeNames<T>
>
