// Auto-generated by generate.py — do not edit

export const DEFINITION = {
	AccessVariable: {
		tag: 'AccessVariable',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['AccessVars'],
		attributes: {
			sequence: ["alias", "direction", "globalId", "instancePathAndName", "pragma"],
			details: {
				alias: { required: true, facets: { whiteSpace: "preserve" } },
				direction: { facets: { enumeration: ["readOnly", "readWrite"], pattern: ["[-.:0-9A-Z_a-z]+"], whiteSpace: "collapse" } },
				globalId: { facets: { pattern: ["[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*", "[A-Za-z_:][-.:0-9A-Z_a-z]*"], whiteSpace: "collapse" } },
				instancePathAndName: { required: true, facets: { whiteSpace: "preserve" } },
				pragma: { facets: { whiteSpace: "preserve" } },
			},
		},
		children: {
			sequence: ["Documentation", "AddData", "UsingDirective", "Type"],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				Type: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
		},
	},
	AccessVars: {
		tag: 'AccessVars',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Program', 'Configuration'],
		attributes: {
			sequence: ["constant", "globalId", "non_retain", "pragma", "retain"],
			details: {
				constant: { default: "false", facets: { whiteSpace: "collapse" } },
				globalId: { facets: { pattern: ["[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*", "[A-Za-z_:][-.:0-9A-Z_a-z]*"], whiteSpace: "collapse" } },
				non_retain: { default: "false", facets: { whiteSpace: "collapse" } },
				pragma: { facets: { whiteSpace: "preserve" } },
				retain: { default: "false", facets: { whiteSpace: "collapse" } },
			},
		},
		children: {
			sequence: ["Documentation", "AddData", "UsingDirective", "Variable"],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				Variable: {},
			},
		},
	},
	Action: {
		tag: 'Action',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Program', 'FunctionBlock'],
		attributes: {
			sequence: ["globalId", "name", "pragma"],
			details: {
				globalId: { facets: { pattern: ["[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*", "[A-Za-z_:][-.:0-9A-Z_a-z]*"], whiteSpace: "collapse" } },
				name: { required: true, facets: { whiteSpace: "preserve" } },
				pragma: { facets: { whiteSpace: "preserve" } },
			},
		},
		children: {
			sequence: ["Documentation", "AddData", "UsingDirective", "Body"],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				Body: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
		},
	},
	AddData: {
		tag: 'AddData',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['FileHeader', 'ContentHeader', 'GlobalNamespace', 'NamespaceDecl', 'DataTypeDecl', 'Program', 'AccessVars', 'Variable', 'Address', 'GlobalVars', 'ExternalVars', 'Vars', 'TempVars', 'MainBody', 'Action', 'Body', 'Transition', 'Condition', 'FunctionBlock', 'Method', 'Class', 'Function', 'Interface', 'Configuration', 'Resource', 'Task', 'ProgramInstance', 'AccessVariable', 'ConfigVars', 'ConfigVariable', 'Project'],
		attributes: {
			sequence: [],
			details: {
			},
		},
		children: {
			sequence: ["Data"],
			details: {
				Data: {},
			},
		},
	},
	AddDataInfo: {
		tag: 'AddDataInfo',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['ContentHeader'],
		attributes: {
			sequence: [],
			details: {
			},
		},
		children: {
			sequence: ["Info"],
			details: {
				Info: {},
			},
		},
	},
	Address: {
		tag: 'Address',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Variable', 'ConfigVariable'],
		attributes: {
			sequence: ["address", "globalId", "location", "notYetFixed", "pragma", "size"],
			details: {
				address: { facets: { whiteSpace: "preserve" } },
				globalId: { facets: { pattern: ["[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*", "[A-Za-z_:][-.:0-9A-Z_a-z]*"], whiteSpace: "collapse" } },
				location: { facets: { enumeration: ["I", "Q", "M"], pattern: ["[-.:0-9A-Z_a-z]+"], whiteSpace: "collapse" } },
				notYetFixed: { default: "false", facets: { whiteSpace: "collapse" } },
				pragma: { facets: { whiteSpace: "preserve" } },
				size: { facets: { enumeration: ["X", "B", "W", "D", "L"], pattern: ["[-.:0-9A-Z_a-z]+"], whiteSpace: "collapse" } },
			},
		},
		children: {
			sequence: ["Documentation", "AddData", "UsingDirective"],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
			},
		},
	},
	ArrayValue: {
		tag: 'ArrayValue',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['InitialValue', 'Value'],
		attributes: {
			sequence: [],
			details: {
			},
		},
		children: {
			sequence: ["Value"],
			details: {
				Value: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
		},
	},
	Body: {
		tag: 'Body',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Action', 'Method'],
		attributes: {
			sequence: ["globalId", "pragma"],
			details: {
				globalId: { facets: { pattern: ["[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*", "[A-Za-z_:][-.:0-9A-Z_a-z]*"], whiteSpace: "collapse" } },
				pragma: { facets: { whiteSpace: "preserve" } },
			},
		},
		children: {
			sequence: ["Documentation", "AddData", "UsingDirective", "BodyContent"],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				BodyContent: {},
			},
		},
	},
	BodyContent: {
		tag: 'BodyContent',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['MainBody', 'Body'],
		attributes: {
			sequence: [],
			details: {
			},
		},
		children: {
			sequence: [],
			details: {
			},
		},
	},
	Class: {
		tag: 'Class',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['NamespaceDecl', 'GlobalNamespace'],
		attributes: {
			sequence: ["abstract", "final", "globalId", "internal", "name", "pragma"],
			details: {
				abstract: { default: "false", facets: { whiteSpace: "collapse" } },
				final: { default: "false", facets: { whiteSpace: "collapse" } },
				globalId: { facets: { pattern: ["[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*", "[A-Za-z_:][-.:0-9A-Z_a-z]*"], whiteSpace: "collapse" } },
				internal: { default: "false", facets: { whiteSpace: "collapse" } },
				name: { required: true, facets: { whiteSpace: "preserve" } },
				pragma: { facets: { whiteSpace: "preserve" } },
			},
		},
		children: {
			sequence: ["Documentation", "AddData", "UsingDirective", "Extends", "Implements", "ExternalVars", "Vars", "Method"],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				Extends: { maxOccurs: 1 },
				Implements: {},
				ExternalVars: {},
				Vars: {},
				Method: {},
			},
		},
	},
	Condition: {
		tag: 'Condition',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Transition'],
		attributes: {
			sequence: ["globalId", "pragma"],
			details: {
				globalId: { facets: { pattern: ["[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*", "[A-Za-z_:][-.:0-9A-Z_a-z]*"], whiteSpace: "collapse" } },
				pragma: { facets: { whiteSpace: "preserve" } },
			},
		},
		children: {
			sequence: ["Documentation", "AddData", "UsingDirective", "PredicateContent"],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				PredicateContent: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
		},
	},
	ConfigVariable: {
		tag: 'ConfigVariable',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['ConfigVars'],
		attributes: {
			sequence: ["globalId", "instancePathAndName", "pragma"],
			details: {
				globalId: { facets: { pattern: ["[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*", "[A-Za-z_:][-.:0-9A-Z_a-z]*"], whiteSpace: "collapse" } },
				instancePathAndName: { required: true, facets: { whiteSpace: "preserve" } },
				pragma: { facets: { whiteSpace: "preserve" } },
			},
		},
		children: {
			sequence: ["Documentation", "AddData", "UsingDirective", "Type", "InitialValue", "Address"],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				Type: { required: true, minOccurs: 1, maxOccurs: 1 },
				InitialValue: { maxOccurs: 1 },
				Address: { maxOccurs: 1 },
			},
		},
	},
	ConfigVars: {
		tag: 'ConfigVars',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Configuration'],
		attributes: {
			sequence: ["globalId", "pragma"],
			details: {
				globalId: { facets: { pattern: ["[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*", "[A-Za-z_:][-.:0-9A-Z_a-z]*"], whiteSpace: "collapse" } },
				pragma: { facets: { whiteSpace: "preserve" } },
			},
		},
		children: {
			sequence: ["Documentation", "AddData", "UsingDirective", "ConfigVariable"],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				ConfigVariable: {},
			},
		},
	},
	Configuration: {
		tag: 'Configuration',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Instances'],
		attributes: {
			sequence: ["globalId", "name", "pragma"],
			details: {
				globalId: { facets: { pattern: ["[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*", "[A-Za-z_:][-.:0-9A-Z_a-z]*"], whiteSpace: "collapse" } },
				name: { required: true, facets: { whiteSpace: "preserve" } },
				pragma: { facets: { whiteSpace: "preserve" } },
			},
		},
		children: {
			sequence: ["Documentation", "AddData", "UsingDirective", "Resource", "GlobalVars", "AccessVars", "ConfigVars"],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				Resource: {},
				GlobalVars: {},
				AccessVars: {},
				ConfigVars: {},
			},
		},
	},
	ContentHeader: {
		tag: 'ContentHeader',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Project'],
		attributes: {
			sequence: ["author", "creationDateTime", "language", "modificationDateTime", "name", "organization", "version"],
			details: {
				author: { facets: { whiteSpace: "preserve" } },
				creationDateTime: { required: true, facets: { whiteSpace: "collapse" } },
				language: { facets: { pattern: ["[a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*"], whiteSpace: "collapse" } },
				modificationDateTime: { facets: { whiteSpace: "collapse" } },
				name: { required: true, facets: { whiteSpace: "preserve" } },
				organization: { facets: { whiteSpace: "preserve" } },
				version: { facets: { whiteSpace: "preserve" } },
			},
		},
		children: {
			sequence: ["CoordinateInfo", "AddDataInfo", "AddData"],
			details: {
				CoordinateInfo: { maxOccurs: 1 },
				AddDataInfo: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
			},
		},
	},
	CoordinateInfo: {
		tag: 'CoordinateInfo',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['ContentHeader'],
		attributes: {
			sequence: [],
			details: {
			},
		},
		children: {
			sequence: ["FbdScaling", "LdScaling", "SfcScaling"],
			details: {
				FbdScaling: { maxOccurs: 1 },
				LdScaling: { maxOccurs: 1 },
				SfcScaling: { maxOccurs: 1 },
			},
		},
	},
	Data: {
		tag: 'Data',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['AddData'],
		attributes: {
			sequence: ["handleUnknown", "name"],
			details: {
				handleUnknown: { required: true, facets: { enumeration: ["preserve", "discard", "implementation"], pattern: ["[-.:0-9A-Z_a-z]+"], whiteSpace: "collapse" } },
				name: { required: true, facets: { whiteSpace: "collapse" } },
			},
		},
		children: {
			sequence: [],
			any: true,
			details: {
			},
		},
	},
	DataTypeDecl: {
		tag: 'DataTypeDecl',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['NamespaceDecl', 'GlobalNamespace'],
		attributes: {
			sequence: ["globalId", "internal", "name", "pragma"],
			details: {
				globalId: { facets: { pattern: ["[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*", "[A-Za-z_:][-.:0-9A-Z_a-z]*"], whiteSpace: "collapse" } },
				internal: { default: "false", facets: { whiteSpace: "collapse" } },
				name: { required: true, facets: { whiteSpace: "preserve" } },
				pragma: { facets: { whiteSpace: "preserve" } },
			},
		},
		children: {
			sequence: ["Documentation", "AddData", "UsingDirective", "UserDefinedTypeSpec"],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				UserDefinedTypeSpec: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
		},
	},
	Description: {
		tag: 'Description',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Info'],
		attributes: {
			sequence: [],
			details: {
			},
		},
		children: {
			sequence: [],
			details: {
			},
		},
	},
	Documentation: {
		tag: 'Documentation',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['GlobalNamespace', 'NamespaceDecl', 'DataTypeDecl', 'Program', 'AccessVars', 'Variable', 'Address', 'GlobalVars', 'ExternalVars', 'Vars', 'TempVars', 'MainBody', 'Action', 'Body', 'Transition', 'Condition', 'FunctionBlock', 'Method', 'Class', 'Function', 'Interface', 'Configuration', 'Resource', 'Task', 'ProgramInstance', 'AccessVariable', 'ConfigVars', 'ConfigVariable', 'Project'],
		attributes: {
			sequence: [],
			details: {
			},
		},
		children: {
			sequence: [],
			details: {
			},
		},
	},
	Extends: {
		tag: 'Extends',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['FunctionBlock', 'Class', 'Interface'],
		attributes: {
			sequence: [],
			details: {
			},
		},
		children: {
			sequence: ["TypeName", "InstantlyDefinedType"],
			details: {
				TypeName: { required: true, minOccurs: 1, maxOccurs: 1 },
				InstantlyDefinedType: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
			choices: [
				{ options: ["InstantlyDefinedType", "TypeName"], minOccurs: 1, maxOccurs: 1 },
			],
		},
	},
	ExternalVars: {
		tag: 'ExternalVars',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Program', 'FunctionBlock', 'Class', 'Function'],
		attributes: {
			sequence: ["constant", "globalId", "pragma"],
			details: {
				constant: { default: "false", facets: { whiteSpace: "collapse" } },
				globalId: { facets: { pattern: ["[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*", "[A-Za-z_:][-.:0-9A-Z_a-z]*"], whiteSpace: "collapse" } },
				pragma: { facets: { whiteSpace: "preserve" } },
			},
		},
		children: {
			sequence: ["Documentation", "AddData", "UsingDirective", "Variable"],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				Variable: {},
			},
		},
	},
	FbInstTaskAssociation: {
		tag: 'FbInstTaskAssociation',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['ProgramInstance'],
		attributes: {
			sequence: ["associatedTaskName", "fbInstanceName"],
			details: {
				associatedTaskName: { required: true, facets: { whiteSpace: "preserve" } },
				fbInstanceName: { required: true, facets: { whiteSpace: "preserve" } },
			},
		},
		children: {
			sequence: [],
			details: {
			},
		},
	},
	FbdScaling: {
		tag: 'FbdScaling',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['CoordinateInfo'],
		attributes: {
			sequence: ["x", "y"],
			details: {
				x: { required: true, facets: { whiteSpace: "collapse" } },
				y: { required: true, facets: { whiteSpace: "collapse" } },
			},
		},
		children: {
			sequence: [],
			details: {
			},
		},
	},
	FileHeader: {
		tag: 'FileHeader',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Project'],
		attributes: {
			sequence: ["companyName", "companyURL", "productName", "productRelease", "productVersion"],
			details: {
				companyName: { required: true, facets: { whiteSpace: "preserve" } },
				companyURL: { facets: { whiteSpace: "collapse" } },
				productName: { required: true, facets: { whiteSpace: "preserve" } },
				productRelease: { facets: { whiteSpace: "preserve" } },
				productVersion: { required: true, facets: { whiteSpace: "preserve" } },
			},
		},
		children: {
			sequence: ["AddData"],
			details: {
				AddData: { maxOccurs: 1 },
			},
		},
	},
	Function: {
		tag: 'Function',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['NamespaceDecl', 'GlobalNamespace'],
		attributes: {
			sequence: ["globalId", "internal", "name", "pragma"],
			details: {
				globalId: { facets: { pattern: ["[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*", "[A-Za-z_:][-.:0-9A-Z_a-z]*"], whiteSpace: "collapse" } },
				internal: { default: "false", facets: { whiteSpace: "collapse" } },
				name: { required: true, facets: { whiteSpace: "preserve" } },
				pragma: { facets: { whiteSpace: "preserve" } },
			},
		},
		children: {
			sequence: ["Documentation", "AddData", "UsingDirective", "ResultType", "Parameters", "ExternalVars", "TempVars", "MainBody"],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				ResultType: { maxOccurs: 1 },
				Parameters: { maxOccurs: 1 },
				ExternalVars: {},
				TempVars: {},
				MainBody: { maxOccurs: 1 },
			},
		},
	},
	FunctionBlock: {
		tag: 'FunctionBlock',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['NamespaceDecl', 'GlobalNamespace'],
		attributes: {
			sequence: ["abstract", "final", "globalId", "internal", "name", "pragma"],
			details: {
				abstract: { default: "false", facets: { whiteSpace: "collapse" } },
				final: { default: "false", facets: { whiteSpace: "collapse" } },
				globalId: { facets: { pattern: ["[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*", "[A-Za-z_:][-.:0-9A-Z_a-z]*"], whiteSpace: "collapse" } },
				internal: { default: "false", facets: { whiteSpace: "collapse" } },
				name: { required: true, facets: { whiteSpace: "preserve" } },
				pragma: { facets: { whiteSpace: "preserve" } },
			},
		},
		children: {
			sequence: ["Documentation", "AddData", "UsingDirective", "Extends", "Implements", "Parameters", "ExternalVars", "Vars", "TempVars", "Method", "MainBody", "Action", "Transition"],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				Extends: { maxOccurs: 1 },
				Implements: {},
				Parameters: { maxOccurs: 1 },
				ExternalVars: {},
				Vars: {},
				TempVars: {},
				Method: {},
				MainBody: { maxOccurs: 1 },
				Action: {},
				Transition: {},
			},
		},
	},
	GlobalNamespace: {
		tag: 'GlobalNamespace',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Types'],
		attributes: {
			sequence: ["globalId", "pragma"],
			details: {
				globalId: { facets: { pattern: ["[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*", "[A-Za-z_:][-.:0-9A-Z_a-z]*"], whiteSpace: "collapse" } },
				pragma: { facets: { whiteSpace: "preserve" } },
			},
		},
		children: {
			sequence: ["Documentation", "AddData", "UsingDirective", "NamespaceDecl", "DataTypeDecl", "Program", "FunctionBlock", "Class", "Function", "Interface"],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				NamespaceDecl: { required: true, minOccurs: 1, maxOccurs: 1 },
				DataTypeDecl: { required: true, minOccurs: 1, maxOccurs: 1 },
				Program: { required: true, minOccurs: 1, maxOccurs: 1 },
				FunctionBlock: { required: true, minOccurs: 1, maxOccurs: 1 },
				Class: { required: true, minOccurs: 1, maxOccurs: 1 },
				Function: { required: true, minOccurs: 1, maxOccurs: 1 },
				Interface: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
			choices: [
				{ options: ["Class", "Function", "FunctionBlock", "Interface", "Program"], minOccurs: 1, maxOccurs: 1 },
				{ options: ["PouDecl"], minOccurs: 1, maxOccurs: 1 },
				{ options: ["DataTypeDecl", "NamespaceDecl", "PouDecl"] },
			],
		},
	},
	GlobalVars: {
		tag: 'GlobalVars',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Program', 'Resource', 'Configuration'],
		attributes: {
			sequence: ["constant", "globalId", "non_retain", "pragma", "retain"],
			details: {
				constant: { default: "false", facets: { whiteSpace: "collapse" } },
				globalId: { facets: { pattern: ["[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*", "[A-Za-z_:][-.:0-9A-Z_a-z]*"], whiteSpace: "collapse" } },
				non_retain: { default: "false", facets: { whiteSpace: "collapse" } },
				pragma: { facets: { whiteSpace: "preserve" } },
				retain: { default: "false", facets: { whiteSpace: "collapse" } },
			},
		},
		children: {
			sequence: ["Documentation", "AddData", "UsingDirective", "Variable"],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				Variable: {},
			},
		},
	},
	Implements: {
		tag: 'Implements',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['FunctionBlock', 'Class'],
		attributes: {
			sequence: [],
			details: {
			},
		},
		children: {
			sequence: ["TypeName", "InstantlyDefinedType"],
			details: {
				TypeName: { required: true, minOccurs: 1, maxOccurs: 1 },
				InstantlyDefinedType: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
			choices: [
				{ options: ["InstantlyDefinedType", "TypeName"], minOccurs: 1, maxOccurs: 1 },
			],
		},
	},
	InOutAssignment: {
		tag: 'InOutAssignment',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['ProgramInstance'],
		attributes: {
			sequence: ["actualValue", "formalParameter"],
			details: {
				actualValue: { required: true, facets: { whiteSpace: "preserve" } },
				formalParameter: { required: true, facets: { whiteSpace: "preserve" } },
			},
		},
		children: {
			sequence: [],
			details: {
			},
		},
	},
	Info: {
		tag: 'Info',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['AddDataInfo'],
		attributes: {
			sequence: ["name", "vendor", "version"],
			details: {
				name: { required: true, facets: { whiteSpace: "collapse" } },
				vendor: { required: true, facets: { whiteSpace: "collapse" } },
				version: { facets: { whiteSpace: "collapse" } },
			},
		},
		children: {
			sequence: ["Description"],
			details: {
				Description: { maxOccurs: 1 },
			},
		},
	},
	InitialValue: {
		tag: 'InitialValue',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Variable', 'ConfigVariable'],
		attributes: {
			sequence: [],
			details: {
			},
		},
		children: {
			sequence: ["SimpleValue", "ArrayValue", "StructValue"],
			details: {
				SimpleValue: { required: true, minOccurs: 1, maxOccurs: 1 },
				ArrayValue: { required: true, minOccurs: 1, maxOccurs: 1 },
				StructValue: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
			choices: [
				{ options: ["ArrayValue", "SimpleValue", "StructValue"], minOccurs: 1, maxOccurs: 1 },
			],
		},
	},
	InoutVars: {
		tag: 'InoutVars',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Parameters'],
		attributes: {
			sequence: [],
			details: {
			},
		},
		children: {
			sequence: ["Variable"],
			details: {
				Variable: {},
			},
		},
	},
	InputAssignment: {
		tag: 'InputAssignment',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['ProgramInstance'],
		attributes: {
			sequence: ["actualValue", "formalParameter"],
			details: {
				actualValue: { required: true, facets: { whiteSpace: "preserve" } },
				formalParameter: { required: true, facets: { whiteSpace: "preserve" } },
			},
		},
		children: {
			sequence: [],
			details: {
			},
		},
	},
	InputVars: {
		tag: 'InputVars',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Parameters'],
		attributes: {
			sequence: ["non_retain", "retain"],
			details: {
				non_retain: { default: "false", facets: { whiteSpace: "collapse" } },
				retain: { default: "false", facets: { whiteSpace: "collapse" } },
			},
		},
		children: {
			sequence: ["Variable"],
			details: {
				Variable: {},
			},
		},
	},
	Instances: {
		tag: 'Instances',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Project'],
		attributes: {
			sequence: [],
			details: {
			},
		},
		children: {
			sequence: ["Configuration"],
			details: {
				Configuration: {},
			},
		},
	},
	InstantlyDefinedType: {
		tag: 'InstantlyDefinedType',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Type', 'Extends', 'Implements', 'ResultType'],
		attributes: {
			sequence: [],
			details: {
			},
		},
		children: {
			sequence: [],
			details: {
			},
		},
	},
	Interface: {
		tag: 'Interface',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['NamespaceDecl', 'GlobalNamespace'],
		attributes: {
			sequence: ["globalId", "internal", "name", "pragma"],
			details: {
				globalId: { facets: { pattern: ["[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*", "[A-Za-z_:][-.:0-9A-Z_a-z]*"], whiteSpace: "collapse" } },
				internal: { default: "false", facets: { whiteSpace: "collapse" } },
				name: { required: true, facets: { whiteSpace: "preserve" } },
				pragma: { facets: { whiteSpace: "preserve" } },
			},
		},
		children: {
			sequence: ["Documentation", "AddData", "UsingDirective", "Extends", "Method"],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				Extends: {},
				Method: {},
			},
		},
	},
	LdScaling: {
		tag: 'LdScaling',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['CoordinateInfo'],
		attributes: {
			sequence: ["x", "y"],
			details: {
				x: { required: true, facets: { whiteSpace: "collapse" } },
				y: { required: true, facets: { whiteSpace: "collapse" } },
			},
		},
		children: {
			sequence: [],
			details: {
			},
		},
	},
	MainBody: {
		tag: 'MainBody',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Program', 'FunctionBlock', 'Function'],
		attributes: {
			sequence: ["globalId", "pragma"],
			details: {
				globalId: { facets: { pattern: ["[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*", "[A-Za-z_:][-.:0-9A-Z_a-z]*"], whiteSpace: "collapse" } },
				pragma: { facets: { whiteSpace: "preserve" } },
			},
		},
		children: {
			sequence: ["Documentation", "AddData", "UsingDirective", "BodyContent"],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				BodyContent: {},
			},
		},
	},
	Method: {
		tag: 'Method',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['FunctionBlock', 'Class', 'Interface'],
		attributes: {
			sequence: ["abstract", "accessSpecifier", "final", "globalId", "name", "override", "pragma"],
			details: {
				abstract: { default: "false", facets: { whiteSpace: "collapse" } },
				accessSpecifier: { required: true, facets: { enumeration: ["private", "protected", "internal", "public"], whiteSpace: "preserve" } },
				final: { default: "false", facets: { whiteSpace: "collapse" } },
				globalId: { facets: { pattern: ["[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*", "[A-Za-z_:][-.:0-9A-Z_a-z]*"], whiteSpace: "collapse" } },
				name: { required: true, facets: { whiteSpace: "preserve" } },
				override: { default: "false", facets: { whiteSpace: "collapse" } },
				pragma: { facets: { whiteSpace: "preserve" } },
			},
		},
		children: {
			sequence: ["Documentation", "AddData", "UsingDirective", "ResultType", "Parameters", "TempVars", "Body"],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				ResultType: { maxOccurs: 1 },
				Parameters: { maxOccurs: 1 },
				TempVars: {},
				Body: { maxOccurs: 1 },
			},
		},
	},
	NamespaceDecl: {
		tag: 'NamespaceDecl',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['GlobalNamespace', 'NamespaceDecl'],
		attributes: {
			sequence: ["globalId", "internal", "name", "pragma"],
			details: {
				globalId: { facets: { pattern: ["[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*", "[A-Za-z_:][-.:0-9A-Z_a-z]*"], whiteSpace: "collapse" } },
				internal: { default: "false", facets: { whiteSpace: "collapse" } },
				name: { required: true, facets: { whiteSpace: "preserve" } },
				pragma: { facets: { whiteSpace: "preserve" } },
			},
		},
		children: {
			sequence: ["Documentation", "AddData", "UsingDirective", "NamespaceDecl", "DataTypeDecl", "Program", "FunctionBlock", "Class", "Function", "Interface"],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				NamespaceDecl: { required: true, minOccurs: 1, maxOccurs: 1 },
				DataTypeDecl: { required: true, minOccurs: 1, maxOccurs: 1 },
				Program: { required: true, minOccurs: 1, maxOccurs: 1 },
				FunctionBlock: { required: true, minOccurs: 1, maxOccurs: 1 },
				Class: { required: true, minOccurs: 1, maxOccurs: 1 },
				Function: { required: true, minOccurs: 1, maxOccurs: 1 },
				Interface: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
			choices: [
				{ options: ["Class", "Function", "FunctionBlock", "Interface", "Program"], minOccurs: 1, maxOccurs: 1 },
				{ options: ["PouDecl"], minOccurs: 1, maxOccurs: 1 },
				{ options: ["DataTypeDecl", "NamespaceDecl", "PouDecl"] },
			],
		},
	},
	OutputAssignment: {
		tag: 'OutputAssignment',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['ProgramInstance'],
		attributes: {
			sequence: ["actualValue", "formalParameter"],
			details: {
				actualValue: { required: true, facets: { whiteSpace: "preserve" } },
				formalParameter: { required: true, facets: { whiteSpace: "preserve" } },
			},
		},
		children: {
			sequence: [],
			details: {
			},
		},
	},
	OutputVars: {
		tag: 'OutputVars',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Parameters'],
		attributes: {
			sequence: ["non_retain", "retain"],
			details: {
				non_retain: { default: "false", facets: { whiteSpace: "collapse" } },
				retain: { default: "false", facets: { whiteSpace: "collapse" } },
			},
		},
		children: {
			sequence: ["Variable"],
			details: {
				Variable: {},
			},
		},
	},
	Parameters: {
		tag: 'Parameters',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Program', 'FunctionBlock', 'Method', 'Function'],
		attributes: {
			sequence: [],
			details: {
			},
		},
		children: {
			sequence: ["InoutVars", "InputVars", "OutputVars"],
			details: {
				InoutVars: { required: true, minOccurs: 1, maxOccurs: 1 },
				InputVars: { required: true, minOccurs: 1, maxOccurs: 1 },
				OutputVars: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
			choices: [
				{ options: ["InoutVars", "InputVars", "OutputVars"] },
			],
		},
	},
	PredicateContent: {
		tag: 'PredicateContent',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Condition'],
		attributes: {
			sequence: [],
			details: {
			},
		},
		children: {
			sequence: [],
			details: {
			},
		},
	},
	Program: {
		tag: 'Program',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['NamespaceDecl', 'GlobalNamespace'],
		attributes: {
			sequence: ["globalId", "internal", "name", "pragma"],
			details: {
				globalId: { facets: { pattern: ["[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*", "[A-Za-z_:][-.:0-9A-Z_a-z]*"], whiteSpace: "collapse" } },
				internal: { default: "false", facets: { whiteSpace: "collapse" } },
				name: { required: true, facets: { whiteSpace: "preserve" } },
				pragma: { facets: { whiteSpace: "preserve" } },
			},
		},
		children: {
			sequence: ["Documentation", "AddData", "UsingDirective", "AccessVars", "GlobalVars", "Parameters", "ExternalVars", "Vars", "TempVars", "MainBody", "Action", "Transition"],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				AccessVars: {},
				GlobalVars: {},
				Parameters: { maxOccurs: 1 },
				ExternalVars: {},
				Vars: {},
				TempVars: {},
				MainBody: { maxOccurs: 1 },
				Action: {},
				Transition: {},
			},
		},
	},
	ProgramInstance: {
		tag: 'ProgramInstance',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Resource'],
		attributes: {
			sequence: ["associatedTaskName", "evaluationOrder", "globalId", "name", "pragma", "typeName"],
			details: {
				associatedTaskName: { facets: { whiteSpace: "preserve" } },
				evaluationOrder: { facets: { minInclusive: 0, maxInclusive: 18446744073709551615, whiteSpace: "collapse" } },
				globalId: { facets: { pattern: ["[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*", "[A-Za-z_:][-.:0-9A-Z_a-z]*"], whiteSpace: "collapse" } },
				name: { required: true, facets: { whiteSpace: "preserve" } },
				pragma: { facets: { whiteSpace: "preserve" } },
				typeName: { required: true, facets: { whiteSpace: "preserve" } },
			},
		},
		children: {
			sequence: ["Documentation", "AddData", "UsingDirective", "InputAssignment", "OutputAssignment", "InOutAssignment", "FbInstTaskAssociation"],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				InputAssignment: {},
				OutputAssignment: {},
				InOutAssignment: {},
				FbInstTaskAssociation: {},
			},
		},
	},
	Project: {
		tag: 'Project',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: [],
		attributes: {
			sequence: ["schemaVersion"],
			details: {
				schemaVersion: { required: true, facets: { whiteSpace: "collapse" } },
			},
		},
		children: {
			sequence: ["FileHeader", "ContentHeader", "Types", "Instances", "AddData", "Documentation"],
			details: {
				FileHeader: { required: true, minOccurs: 1, maxOccurs: 1 },
				ContentHeader: { required: true, minOccurs: 1, maxOccurs: 1 },
				Types: { required: true, minOccurs: 1, maxOccurs: 1 },
				Instances: { required: true, minOccurs: 1, maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				Documentation: { maxOccurs: 1 },
			},
		},
	},
	Resource: {
		tag: 'Resource',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Configuration'],
		attributes: {
			sequence: ["globalId", "name", "pragma", "resourceTypeName"],
			details: {
				globalId: { facets: { pattern: ["[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*", "[A-Za-z_:][-.:0-9A-Z_a-z]*"], whiteSpace: "collapse" } },
				name: { required: true, facets: { whiteSpace: "preserve" } },
				pragma: { facets: { whiteSpace: "preserve" } },
				resourceTypeName: { required: true, facets: { whiteSpace: "preserve" } },
			},
		},
		children: {
			sequence: ["Documentation", "AddData", "UsingDirective", "GlobalVars", "Task", "ProgramInstance"],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				GlobalVars: {},
				Task: {},
				ProgramInstance: {},
			},
		},
	},
	ResultType: {
		tag: 'ResultType',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Method', 'Function'],
		attributes: {
			sequence: [],
			details: {
			},
		},
		children: {
			sequence: ["TypeName", "InstantlyDefinedType"],
			details: {
				TypeName: { required: true, minOccurs: 1, maxOccurs: 1 },
				InstantlyDefinedType: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
			choices: [
				{ options: ["InstantlyDefinedType", "TypeName"], minOccurs: 1, maxOccurs: 1 },
			],
		},
	},
	SfcScaling: {
		tag: 'SfcScaling',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['CoordinateInfo'],
		attributes: {
			sequence: ["x", "y"],
			details: {
				x: { required: true, facets: { whiteSpace: "collapse" } },
				y: { required: true, facets: { whiteSpace: "collapse" } },
			},
		},
		children: {
			sequence: [],
			details: {
			},
		},
	},
	SimpleValue: {
		tag: 'SimpleValue',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['InitialValue', 'Value'],
		attributes: {
			sequence: ["value"],
			details: {
				value: { facets: { whiteSpace: "preserve" } },
			},
		},
		children: {
			sequence: [],
			details: {
			},
		},
	},
	StructValue: {
		tag: 'StructValue',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Value', 'InitialValue'],
		attributes: {
			sequence: [],
			details: {
			},
		},
		children: {
			sequence: ["Value"],
			details: {
				Value: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
		},
	},
	Task: {
		tag: 'Task',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Resource'],
		attributes: {
			sequence: ["globalId", "name", "pragma"],
			details: {
				globalId: { facets: { pattern: ["[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*", "[A-Za-z_:][-.:0-9A-Z_a-z]*"], whiteSpace: "collapse" } },
				name: { required: true, facets: { whiteSpace: "preserve" } },
				pragma: { facets: { whiteSpace: "preserve" } },
			},
		},
		children: {
			sequence: ["Documentation", "AddData", "UsingDirective"],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
			},
		},
	},
	TempVars: {
		tag: 'TempVars',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Program', 'FunctionBlock', 'Method', 'Function'],
		attributes: {
			sequence: ["constant", "globalId", "non_retain", "pragma", "retain"],
			details: {
				constant: { default: "false", facets: { whiteSpace: "collapse" } },
				globalId: { facets: { pattern: ["[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*", "[A-Za-z_:][-.:0-9A-Z_a-z]*"], whiteSpace: "collapse" } },
				non_retain: { default: "false", facets: { whiteSpace: "collapse" } },
				pragma: { facets: { whiteSpace: "preserve" } },
				retain: { default: "false", facets: { whiteSpace: "collapse" } },
			},
		},
		children: {
			sequence: ["Documentation", "AddData", "UsingDirective", "Variable"],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				Variable: {},
			},
		},
	},
	Transition: {
		tag: 'Transition',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Program', 'FunctionBlock'],
		attributes: {
			sequence: ["globalId", "name", "pragma"],
			details: {
				globalId: { facets: { pattern: ["[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*", "[A-Za-z_:][-.:0-9A-Z_a-z]*"], whiteSpace: "collapse" } },
				name: { required: true, facets: { whiteSpace: "preserve" } },
				pragma: { facets: { whiteSpace: "preserve" } },
			},
		},
		children: {
			sequence: ["Documentation", "AddData", "UsingDirective", "Condition"],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				Condition: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
		},
	},
	Type: {
		tag: 'Type',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Variable', 'AccessVariable', 'ConfigVariable'],
		attributes: {
			sequence: [],
			details: {
			},
		},
		children: {
			sequence: ["TypeName", "InstantlyDefinedType"],
			details: {
				TypeName: { required: true, minOccurs: 1, maxOccurs: 1 },
				InstantlyDefinedType: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
			choices: [
				{ options: ["InstantlyDefinedType", "TypeName"], minOccurs: 1, maxOccurs: 1 },
			],
		},
	},
	TypeName: {
		tag: 'TypeName',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Type', 'Extends', 'Implements', 'ResultType'],
		attributes: {
			sequence: [],
			details: {
			},
		},
		children: {
			sequence: [],
			details: {
			},
		},
		textContent: { facets: { whiteSpace: "preserve" } },
	},
	Types: {
		tag: 'Types',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Project'],
		attributes: {
			sequence: [],
			details: {
			},
		},
		children: {
			sequence: ["GlobalNamespace"],
			details: {
				GlobalNamespace: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
		},
	},
	UserDefinedTypeSpec: {
		tag: 'UserDefinedTypeSpec',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['DataTypeDecl'],
		attributes: {
			sequence: [],
			details: {
			},
		},
		children: {
			sequence: [],
			details: {
			},
		},
	},
	UsingDirective: {
		tag: 'UsingDirective',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['GlobalNamespace', 'NamespaceDecl', 'DataTypeDecl', 'Program', 'AccessVars', 'Variable', 'Address', 'GlobalVars', 'ExternalVars', 'Vars', 'TempVars', 'MainBody', 'Action', 'Body', 'Transition', 'Condition', 'FunctionBlock', 'Method', 'Class', 'Function', 'Interface', 'Configuration', 'Resource', 'Task', 'ProgramInstance', 'AccessVariable', 'ConfigVars', 'ConfigVariable'],
		attributes: {
			sequence: [],
			details: {
			},
		},
		children: {
			sequence: [],
			details: {
			},
		},
		textContent: { facets: { whiteSpace: "preserve" } },
	},
	Value: {
		tag: 'Value',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['ArrayValue', 'StructValue'],
		attributes: {
			sequence: ["repetitionValue"],
			details: {
				repetitionValue: { default: "1", facets: { whiteSpace: "preserve" } },
			},
		},
		children: {
			sequence: ["SimpleValue", "ArrayValue", "StructValue"],
			details: {
				SimpleValue: { required: true, minOccurs: 1, maxOccurs: 1 },
				ArrayValue: { required: true, minOccurs: 1, maxOccurs: 1 },
				StructValue: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
			choices: [
				{ options: ["ArrayValue", "SimpleValue", "StructValue"], minOccurs: 1, maxOccurs: 1 },
			],
		},
	},
	Variable: {
		tag: 'Variable',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['AccessVars', 'GlobalVars', 'InoutVars', 'InputVars', 'OutputVars', 'ExternalVars', 'Vars', 'TempVars'],
		attributes: {
			sequence: ["globalId", "name", "pragma"],
			details: {
				globalId: { facets: { pattern: ["[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*", "[A-Za-z_:][-.:0-9A-Z_a-z]*"], whiteSpace: "collapse" } },
				name: { required: true, facets: { whiteSpace: "preserve" } },
				pragma: { facets: { whiteSpace: "preserve" } },
			},
		},
		children: {
			sequence: ["Documentation", "AddData", "UsingDirective", "Type", "InitialValue", "Address"],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				Type: { required: true, minOccurs: 1, maxOccurs: 1 },
				InitialValue: { maxOccurs: 1 },
				Address: { maxOccurs: 1 },
			},
		},
	},
	Vars: {
		tag: 'Vars',
		namespace: { prefix: "ppx", uri: "www.iec.ch/public/TC65SC65BWG7TF10" },
		parents: ['Program', 'FunctionBlock', 'Class'],
		attributes: {
			sequence: ["accessSpecifier", "constant", "globalId", "non_retain", "pragma", "retain"],
			details: {
				accessSpecifier: { required: true, facets: { enumeration: ["private", "protected", "internal", "public"], whiteSpace: "preserve" } },
				constant: { default: "false", facets: { whiteSpace: "collapse" } },
				globalId: { facets: { pattern: ["[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*", "[A-Za-z_:][-.:0-9A-Z_a-z]*"], whiteSpace: "collapse" } },
				non_retain: { default: "false", facets: { whiteSpace: "collapse" } },
				pragma: { facets: { whiteSpace: "preserve" } },
				retain: { default: "false", facets: { whiteSpace: "collapse" } },
			},
		},
		children: {
			sequence: ["Documentation", "AddData", "UsingDirective", "Variable"],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				Variable: {},
			},
		},
	},
} as const
