// Auto-generated by generate.py — do not edit

export const DEFINITION = {
	AccessVariable: {
		tag: 'AccessVariable',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['AccessVars'],
		attributes: {
			sequence: ['alias', 'direction', 'globalId', 'instancePathAndName', 'pragma'],
			details: {
				alias: { required: true, facets: { whiteSpace: 'preserve' } },
				direction: {
					facets: {
						enumeration: ['readOnly', 'readWrite'],
						pattern: ['[-.:0-9A-Z_a-z]+'],
						whiteSpace: 'collapse',
					},
				},
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				instancePathAndName: { required: true, facets: { whiteSpace: 'preserve' } },
				pragma: { facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: ['Documentation', 'AddData', 'UsingDirective', 'Type'],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				Type: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
		},
	},
	AccessVars: {
		tag: 'AccessVars',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Program', 'Configuration'],
		attributes: {
			sequence: [
				'accessSpecifier',
				'constant',
				'globalId',
				'non_retain',
				'pragma',
				'retain',
				'xsi:type',
			],
			details: {
				accessSpecifier: {
					facets: {
						enumeration: ['private', 'protected', 'internal', 'public'],
						whiteSpace: 'preserve',
					},
				},
				constant: { default: 'false', facets: { whiteSpace: 'collapse' } },
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				non_retain: { default: 'false', facets: { whiteSpace: 'collapse' } },
				pragma: { facets: { whiteSpace: 'preserve' } },
				retain: { default: 'false', facets: { whiteSpace: 'collapse' } },
				'xsi:type': {
					namespace: { prefix: 'xsi', uri: 'http://www.w3.org/2001/XMLSchema-instance' },
					facets: { enumeration: ['VarListWithAccessSpec'] },
				},
			},
		},
		children: {
			sequence: ['Documentation', 'AddData', 'UsingDirective', 'Variable'],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				Variable: {},
			},
		},
	},
	Action: {
		tag: 'Action',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Program', 'FunctionBlock'],
		attributes: {
			sequence: ['globalId', 'name', 'pragma'],
			details: {
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				name: { required: true, facets: { whiteSpace: 'preserve' } },
				pragma: { facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: ['Documentation', 'AddData', 'UsingDirective', 'Body'],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				Body: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
		},
	},
	ActionBlock: {
		tag: 'ActionBlock',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['CommonObject'],
		attributes: {
			sequence: ['globalId', 'indicator'],
			details: {
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				indicator: { facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: [
				'Documentation',
				'AddData',
				'RelPosition',
				'Size',
				'ActionQualifier',
				'Inline',
				'ComplexOperand',
				'ReferenceName',
			],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				RelPosition: { maxOccurs: 1 },
				Size: { maxOccurs: 1 },
				ActionQualifier: { maxOccurs: 1 },
				Inline: { required: true, minOccurs: 1, maxOccurs: 1 },
				ComplexOperand: { required: true, minOccurs: 1, maxOccurs: 1 },
				ReferenceName: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
			choices: [
				{ options: ['ComplexOperand', 'Inline', 'ReferenceName'], minOccurs: 1, maxOccurs: 1 },
			],
		},
	},
	ActionQualifier: {
		tag: 'ActionQualifier',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['ActionBlock'],
		attributes: {
			sequence: ['duration', 'qualifier'],
			details: {
				duration: { facets: { whiteSpace: 'preserve' } },
				qualifier: {
					default: 'N',
					facets: {
						enumeration: ['P1', 'N', 'P0', 'R', 'S', 'L', 'D', 'P', 'DS', 'DL', 'SD', 'SL'],
						pattern: ['[-.:0-9A-Z_a-z]+'],
						whiteSpace: 'collapse',
					},
				},
			},
		},
		children: {
			sequence: [],
			details: {},
		},
	},
	AddData: {
		tag: 'AddData',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: [
			'FileHeader',
			'ContentHeader',
			'GlobalNamespace',
			'NamespaceDecl',
			'DataTypeDecl',
			'InstantlyDefinedType',
			'UserDefinedTypeSpec',
			'Member',
			'Address',
			'Program',
			'AccessVars',
			'Variable',
			'GlobalVars',
			'ExternalVars',
			'Vars',
			'TempVars',
			'MainBody',
			'Network',
			'CommonObject',
			'ConnectionPointIn',
			'Connection',
			'FeedbackConnection',
			'ActionBlock',
			'Inline',
			'ConnectionPointOut',
			'FbdObject',
			'InOutVariable',
			'InputVariable',
			'OutputVariable',
			'Rung',
			'LdObject',
			'SfcObject',
			'ConnectionPointOutAction',
			'GraphicalExpression',
			'TextualPredicate',
			'Action',
			'Body',
			'Transition',
			'Condition',
			'FunctionBlock',
			'Method',
			'Class',
			'Function',
			'Interface',
			'Configuration',
			'Resource',
			'Task',
			'ProgramInstance',
			'AccessVariable',
			'ConfigVars',
			'ConfigVariable',
			'Project',
		],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['Data'],
			details: {
				Data: {},
			},
		},
	},
	AddDataInfo: {
		tag: 'AddDataInfo',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['ContentHeader'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['Info'],
			details: {
				Info: {},
			},
		},
	},
	Address: {
		tag: 'Address',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Member', 'Variable', 'ConfigVariable'],
		attributes: {
			sequence: ['address', 'globalId', 'location', 'notYetFixed', 'pragma', 'size', 'xsi:type'],
			details: {
				address: { facets: { whiteSpace: 'preserve' } },
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				location: {
					facets: {
						enumeration: ['I', 'Q', 'M'],
						pattern: ['[-.:0-9A-Z_a-z]+'],
						whiteSpace: 'collapse',
					},
				},
				notYetFixed: { default: 'false', facets: { whiteSpace: 'collapse' } },
				pragma: { facets: { whiteSpace: 'preserve' } },
				size: {
					facets: {
						enumeration: ['X', 'B', 'W', 'D', 'L'],
						pattern: ['[-.:0-9A-Z_a-z]+'],
						whiteSpace: 'collapse',
					},
				},
				'xsi:type': {
					namespace: { prefix: 'xsi', uri: 'http://www.w3.org/2001/XMLSchema-instance' },
					facets: { enumeration: ['AddressExpression'] },
				},
			},
		},
		children: {
			sequence: ['Documentation', 'AddData', 'UsingDirective'],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
			},
		},
	},
	ArrayValue: {
		tag: 'ArrayValue',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['InitialValue', 'Value'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['Value'],
			details: {
				Value: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
		},
	},
	BaseType: {
		tag: 'BaseType',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['UserDefinedTypeSpec', 'InstantlyDefinedType'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['TypeName', 'InstantlyDefinedType'],
			details: {
				TypeName: { required: true, minOccurs: 1, maxOccurs: 1 },
				InstantlyDefinedType: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
			choices: [{ options: ['InstantlyDefinedType', 'TypeName'], minOccurs: 1, maxOccurs: 1 }],
		},
	},
	Body: {
		tag: 'Body',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Action', 'Method'],
		attributes: {
			sequence: ['globalId', 'pragma'],
			details: {
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				pragma: { facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: ['Documentation', 'AddData', 'UsingDirective', 'BodyContent'],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				BodyContent: {},
			},
		},
	},
	BodyContent: {
		tag: 'BodyContent',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['MainBody', 'Inline', 'Body'],
		attributes: {
			sequence: ['xsi:type'],
			details: {
				'xsi:type': {
					namespace: { prefix: 'xsi', uri: 'http://www.w3.org/2001/XMLSchema-instance' },
					facets: { enumeration: ['FBD', 'IL', 'LD', 'SFC', 'ST'] },
				},
			},
		},
		children: {
			sequence: [
				'Network',
				'IL',
				'Rung',
				'CommonObject',
				'LdObject',
				'FbdObject',
				'SfcObject',
				'ST',
			],
			details: {
				Network: {},
				IL: { maxOccurs: 1 },
				Rung: {},
				CommonObject: { maxOccurs: 1 },
				LdObject: { maxOccurs: 1 },
				FbdObject: { maxOccurs: 1 },
				SfcObject: { maxOccurs: 1 },
				ST: { maxOccurs: 1 },
			},
		},
	},
	Class: {
		tag: 'Class',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['NamespaceDecl', 'GlobalNamespace'],
		attributes: {
			sequence: ['abstract', 'final', 'globalId', 'internal', 'name', 'pragma'],
			details: {
				abstract: { default: 'false', facets: { whiteSpace: 'collapse' } },
				final: { default: 'false', facets: { whiteSpace: 'collapse' } },
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				internal: { default: 'false', facets: { whiteSpace: 'collapse' } },
				name: { required: true, facets: { whiteSpace: 'preserve' } },
				pragma: { facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: [
				'Documentation',
				'AddData',
				'UsingDirective',
				'Extends',
				'Implements',
				'ExternalVars',
				'Vars',
				'Method',
			],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				Extends: { maxOccurs: 1 },
				Implements: {},
				ExternalVars: {},
				Vars: {},
				Method: {},
			},
		},
	},
	CommonObject: {
		tag: 'CommonObject',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Network', 'Rung', 'BodyContent', 'GraphicalExpression'],
		attributes: {
			sequence: ['globalId', 'label', 'xsi:type'],
			details: {
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				label: { facets: { whiteSpace: 'preserve' } },
				'xsi:type': {
					namespace: { prefix: 'xsi', uri: 'http://www.w3.org/2001/XMLSchema-instance' },
					facets: { enumeration: ['ActionBlocks', 'Comment', 'Connector', 'Continuation'] },
				},
			},
		},
		children: {
			sequence: [
				'Documentation',
				'AddData',
				'RelPosition',
				'Size',
				'ConnectionPointIn',
				'ActionBlock',
				'Content',
				'ConnectionPointOut',
			],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				RelPosition: { maxOccurs: 1 },
				Size: { maxOccurs: 1 },
				ConnectionPointIn: { maxOccurs: 1 },
				ActionBlock: {},
				Content: { maxOccurs: 1 },
				ConnectionPointOut: { maxOccurs: 1 },
			},
		},
	},
	ComplexOperand: {
		tag: 'ComplexOperand',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['ActionBlock'],
		attributes: {
			sequence: ['xsi:type'],
			details: {
				'xsi:type': {
					namespace: { prefix: 'xsi', uri: 'http://www.w3.org/2001/XMLSchema-instance' },
					facets: { enumeration: ['AccessSpecifiers', 'EdgeModifierType'] },
				},
			},
		},
		children: {
			sequence: [],
			details: {},
		},
		textContent: { facets: { whiteSpace: 'preserve' } },
	},
	Condition: {
		tag: 'Condition',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['SfcObject', 'Transition'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['Reference', 'GraphicalPredicate', 'TextualPredicate'],
			details: {
				Reference: { required: true, minOccurs: 1, maxOccurs: 1 },
				GraphicalPredicate: { required: true, minOccurs: 1, maxOccurs: 1 },
				TextualPredicate: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
			choices: [
				{
					options: ['GraphicalPredicate', 'Reference', 'TextualPredicate'],
					minOccurs: 1,
					maxOccurs: 1,
				},
			],
		},
	},
	ConfigVariable: {
		tag: 'ConfigVariable',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['ConfigVars'],
		attributes: {
			sequence: ['globalId', 'instancePathAndName', 'pragma'],
			details: {
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				instancePathAndName: { required: true, facets: { whiteSpace: 'preserve' } },
				pragma: { facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: ['Documentation', 'AddData', 'UsingDirective', 'Type', 'InitialValue', 'Address'],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				Type: { required: true, minOccurs: 1, maxOccurs: 1 },
				InitialValue: { maxOccurs: 1 },
				Address: { maxOccurs: 1 },
			},
		},
	},
	ConfigVars: {
		tag: 'ConfigVars',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Configuration'],
		attributes: {
			sequence: ['globalId', 'pragma'],
			details: {
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				pragma: { facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: ['Documentation', 'AddData', 'UsingDirective', 'ConfigVariable'],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				ConfigVariable: {},
			},
		},
	},
	Configuration: {
		tag: 'Configuration',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Instances'],
		attributes: {
			sequence: ['globalId', 'name', 'pragma'],
			details: {
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				name: { required: true, facets: { whiteSpace: 'preserve' } },
				pragma: { facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: [
				'Documentation',
				'AddData',
				'UsingDirective',
				'Resource',
				'GlobalVars',
				'AccessVars',
				'ConfigVars',
			],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				Resource: {},
				GlobalVars: {},
				AccessVars: {},
				ConfigVars: {},
			},
		},
	},
	Connection: {
		tag: 'Connection',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['ConnectionPointIn'],
		attributes: {
			sequence: ['feedbackVariable', 'globalId', 'refConnectionPointOutId', 'xsi:type'],
			details: {
				feedbackVariable: { facets: { whiteSpace: 'preserve' } },
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				refConnectionPointOutId: {
					required: true,
					facets: { minInclusive: 0, maxInclusive: 18446744073709551615, whiteSpace: 'collapse' },
				},
				'xsi:type': {
					namespace: { prefix: 'xsi', uri: 'http://www.w3.org/2001/XMLSchema-instance' },
					facets: { enumeration: ['FeedbackConnection'] },
				},
			},
		},
		children: {
			sequence: ['Documentation', 'AddData', 'RelPosition'],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				RelPosition: {},
			},
		},
	},
	ConnectionPointIn: {
		tag: 'ConnectionPointIn',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: [
			'CommonObject',
			'InOutVariable',
			'InputVariable',
			'FbdObject',
			'LdObject',
			'SfcObject',
			'GraphicalPredicate',
		],
		attributes: {
			sequence: ['globalId'],
			details: {
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
			},
		},
		children: {
			sequence: ['Documentation', 'AddData', 'RelPosition', 'Connection', 'FeedbackConnection'],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				RelPosition: { maxOccurs: 1 },
				Connection: {},
				FeedbackConnection: {},
			},
			choices: [{ options: ['Connection', 'FeedbackConnection'], minOccurs: 1, maxOccurs: 1 }],
		},
	},
	ConnectionPointOut: {
		tag: 'ConnectionPointOut',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: [
			'CommonObject',
			'InOutVariable',
			'OutputVariable',
			'FbdObject',
			'LdObject',
			'SfcObject',
		],
		attributes: {
			sequence: ['connectionPointOutId', 'globalId'],
			details: {
				connectionPointOutId: {
					required: true,
					facets: { minInclusive: 0, maxInclusive: 18446744073709551615, whiteSpace: 'collapse' },
				},
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
			},
		},
		children: {
			sequence: ['Documentation', 'AddData', 'RelPosition'],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				RelPosition: { maxOccurs: 1 },
			},
		},
	},
	ConnectionPointOutAction: {
		tag: 'ConnectionPointOutAction',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['SfcObject'],
		attributes: {
			sequence: ['connectionPointOutId', 'globalId'],
			details: {
				connectionPointOutId: {
					required: true,
					facets: { minInclusive: 0, maxInclusive: 18446744073709551615, whiteSpace: 'collapse' },
				},
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
			},
		},
		children: {
			sequence: ['Documentation', 'AddData', 'RelPosition'],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				RelPosition: { maxOccurs: 1 },
			},
		},
	},
	Content: {
		tag: 'Content',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['CommonObject'],
		attributes: {
			sequence: ['xsi:type'],
			details: {
				'xsi:type': {
					namespace: { prefix: 'xsi', uri: 'http://www.w3.org/2001/XMLSchema-instance' },
					facets: { enumeration: ['SimpleText'] },
				},
			},
		},
		children: {
			sequence: [],
			details: {},
		},
	},
	ContentHeader: {
		tag: 'ContentHeader',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Project'],
		attributes: {
			sequence: [
				'author',
				'creationDateTime',
				'language',
				'modificationDateTime',
				'name',
				'organization',
				'version',
			],
			details: {
				author: { facets: { whiteSpace: 'preserve' } },
				creationDateTime: { required: true, facets: { whiteSpace: 'collapse' } },
				language: {
					facets: { pattern: ['[a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*'], whiteSpace: 'collapse' },
				},
				modificationDateTime: { facets: { whiteSpace: 'collapse' } },
				name: { required: true, facets: { whiteSpace: 'preserve' } },
				organization: { facets: { whiteSpace: 'preserve' } },
				version: { facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: ['CoordinateInfo', 'AddDataInfo', 'AddData'],
			details: {
				CoordinateInfo: { maxOccurs: 1 },
				AddDataInfo: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
			},
		},
	},
	CoordinateInfo: {
		tag: 'CoordinateInfo',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['ContentHeader'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['FbdScaling', 'LdScaling', 'SfcScaling'],
			details: {
				FbdScaling: { maxOccurs: 1 },
				LdScaling: { maxOccurs: 1 },
				SfcScaling: { maxOccurs: 1 },
			},
		},
	},
	Data: {
		tag: 'Data',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['AddData'],
		attributes: {
			sequence: ['handleUnknown', 'name'],
			details: {
				handleUnknown: {
					required: true,
					facets: {
						enumeration: ['preserve', 'discard', 'implementation'],
						pattern: ['[-.:0-9A-Z_a-z]+'],
						whiteSpace: 'collapse',
					},
				},
				name: { required: true, facets: { whiteSpace: 'collapse' } },
			},
		},
		children: {
			sequence: [],
			any: true,
			details: {},
		},
	},
	DataTypeDecl: {
		tag: 'DataTypeDecl',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['NamespaceDecl', 'GlobalNamespace'],
		attributes: {
			sequence: ['globalId', 'internal', 'name', 'pragma'],
			details: {
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				internal: { default: 'false', facets: { whiteSpace: 'collapse' } },
				name: { required: true, facets: { whiteSpace: 'preserve' } },
				pragma: { facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: ['Documentation', 'AddData', 'UsingDirective', 'UserDefinedTypeSpec'],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				UserDefinedTypeSpec: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
		},
	},
	Description: {
		tag: 'Description',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Info'],
		attributes: {
			sequence: ['xsi:type'],
			details: {
				'xsi:type': {
					namespace: { prefix: 'xsi', uri: 'http://www.w3.org/2001/XMLSchema-instance' },
					facets: { enumeration: ['SimpleText'] },
				},
			},
		},
		children: {
			sequence: [],
			details: {},
		},
	},
	DimensionSpec: {
		tag: 'DimensionSpec',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['InstantlyDefinedType', 'UserDefinedTypeSpec'],
		attributes: {
			sequence: ['dimensionNumber'],
			details: {
				dimensionNumber: {
					required: true,
					facets: { minInclusive: 0, maxInclusive: 4294967295, whiteSpace: 'collapse' },
				},
			},
		},
		children: {
			sequence: ['IndexRange', 'VariableLength'],
			details: {
				IndexRange: { required: true, minOccurs: 1, maxOccurs: 1 },
				VariableLength: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
			choices: [{ options: ['IndexRange', 'VariableLength'], minOccurs: 1, maxOccurs: 1 }],
		},
	},
	Documentation: {
		tag: 'Documentation',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: [
			'GlobalNamespace',
			'NamespaceDecl',
			'DataTypeDecl',
			'Enumerator',
			'Member',
			'Address',
			'Program',
			'AccessVars',
			'Variable',
			'GlobalVars',
			'ExternalVars',
			'Vars',
			'TempVars',
			'MainBody',
			'Network',
			'CommonObject',
			'ConnectionPointIn',
			'Connection',
			'FeedbackConnection',
			'ActionBlock',
			'Inline',
			'ConnectionPointOut',
			'FbdObject',
			'InOutVariable',
			'InputVariable',
			'OutputVariable',
			'Rung',
			'LdObject',
			'SfcObject',
			'ConnectionPointOutAction',
			'GraphicalExpression',
			'TextualPredicate',
			'Action',
			'Body',
			'Transition',
			'Condition',
			'FunctionBlock',
			'Method',
			'Class',
			'Function',
			'Interface',
			'Configuration',
			'Resource',
			'Task',
			'ProgramInstance',
			'AccessVariable',
			'ConfigVars',
			'ConfigVariable',
			'Project',
		],
		attributes: {
			sequence: ['xsi:type'],
			details: {
				'xsi:type': {
					namespace: { prefix: 'xsi', uri: 'http://www.w3.org/2001/XMLSchema-instance' },
					facets: { enumeration: ['SimpleText'] },
				},
			},
		},
		children: {
			sequence: [],
			details: {},
		},
	},
	Enumerator: {
		tag: 'Enumerator',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['UserDefinedTypeSpec'],
		attributes: {
			sequence: ['name'],
			details: {
				name: { required: true, facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: ['Documentation'],
			details: {
				Documentation: { maxOccurs: 1 },
			},
		},
	},
	Extends: {
		tag: 'Extends',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['FunctionBlock', 'Class', 'Interface'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['TypeName', 'InstantlyDefinedType'],
			details: {
				TypeName: { required: true, minOccurs: 1, maxOccurs: 1 },
				InstantlyDefinedType: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
			choices: [{ options: ['InstantlyDefinedType', 'TypeName'], minOccurs: 1, maxOccurs: 1 }],
		},
	},
	ExternalVars: {
		tag: 'ExternalVars',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Program', 'FunctionBlock', 'Class', 'Function'],
		attributes: {
			sequence: ['constant', 'globalId', 'pragma'],
			details: {
				constant: { default: 'false', facets: { whiteSpace: 'collapse' } },
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				pragma: { facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: ['Documentation', 'AddData', 'UsingDirective', 'Variable'],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				Variable: {},
			},
		},
	},
	FbInstTaskAssociation: {
		tag: 'FbInstTaskAssociation',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['ProgramInstance'],
		attributes: {
			sequence: ['associatedTaskName', 'fbInstanceName'],
			details: {
				associatedTaskName: { required: true, facets: { whiteSpace: 'preserve' } },
				fbInstanceName: { required: true, facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: [],
			details: {},
		},
	},
	FbdObject: {
		tag: 'FbdObject',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Network', 'Rung', 'BodyContent', 'GraphicalExpression'],
		attributes: {
			sequence: [
				'complexIdentifier',
				'globalId',
				'identifier',
				'instanceName',
				'targetNetworkLabel',
				'typeName',
				'xsi:type',
			],
			details: {
				complexIdentifier: { facets: { whiteSpace: 'preserve' } },
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				identifier: { facets: { whiteSpace: 'preserve' } },
				instanceName: { facets: { whiteSpace: 'preserve' } },
				targetNetworkLabel: { facets: { whiteSpace: 'preserve' } },
				typeName: { facets: { whiteSpace: 'preserve' } },
				'xsi:type': {
					namespace: { prefix: 'xsi', uri: 'http://www.w3.org/2001/XMLSchema-instance' },
					facets: {
						enumeration: ['Block', 'DataSink', 'DataSource', 'Jump', 'Return', 'Unconnected'],
					},
				},
			},
		},
		children: {
			sequence: [
				'Documentation',
				'AddData',
				'RelPosition',
				'Size',
				'InOutVariables',
				'InputVariables',
				'OutputVariables',
				'ConnectionPointIn',
				'ConnectionPointOut',
			],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				RelPosition: { maxOccurs: 1 },
				Size: { maxOccurs: 1 },
				InOutVariables: { maxOccurs: 1 },
				InputVariables: { maxOccurs: 1 },
				OutputVariables: { maxOccurs: 1 },
				ConnectionPointIn: { maxOccurs: 1 },
				ConnectionPointOut: { maxOccurs: 1 },
			},
		},
	},
	FbdScaling: {
		tag: 'FbdScaling',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['CoordinateInfo'],
		attributes: {
			sequence: ['x', 'y'],
			details: {
				x: { required: true, facets: { whiteSpace: 'collapse' } },
				y: { required: true, facets: { whiteSpace: 'collapse' } },
			},
		},
		children: {
			sequence: [],
			details: {},
		},
	},
	FeedbackConnection: {
		tag: 'FeedbackConnection',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['ConnectionPointIn'],
		attributes: {
			sequence: ['feedbackVariable', 'globalId', 'refConnectionPointOutId'],
			details: {
				feedbackVariable: { required: true, facets: { whiteSpace: 'preserve' } },
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				refConnectionPointOutId: {
					required: true,
					facets: { minInclusive: 0, maxInclusive: 18446744073709551615, whiteSpace: 'collapse' },
				},
			},
		},
		children: {
			sequence: ['Documentation', 'AddData', 'RelPosition'],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				RelPosition: {},
			},
		},
	},
	FileHeader: {
		tag: 'FileHeader',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Project'],
		attributes: {
			sequence: ['companyName', 'companyURL', 'productName', 'productRelease', 'productVersion'],
			details: {
				companyName: { required: true, facets: { whiteSpace: 'preserve' } },
				companyURL: { facets: { whiteSpace: 'collapse' } },
				productName: { required: true, facets: { whiteSpace: 'preserve' } },
				productRelease: { facets: { whiteSpace: 'preserve' } },
				productVersion: { required: true, facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: ['AddData'],
			details: {
				AddData: { maxOccurs: 1 },
			},
		},
	},
	Function: {
		tag: 'Function',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['NamespaceDecl', 'GlobalNamespace'],
		attributes: {
			sequence: ['globalId', 'internal', 'name', 'pragma'],
			details: {
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				internal: { default: 'false', facets: { whiteSpace: 'collapse' } },
				name: { required: true, facets: { whiteSpace: 'preserve' } },
				pragma: { facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: [
				'Documentation',
				'AddData',
				'UsingDirective',
				'ResultType',
				'Parameters',
				'ExternalVars',
				'TempVars',
				'MainBody',
			],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				ResultType: { maxOccurs: 1 },
				Parameters: { maxOccurs: 1 },
				ExternalVars: {},
				TempVars: {},
				MainBody: { maxOccurs: 1 },
			},
		},
	},
	FunctionBlock: {
		tag: 'FunctionBlock',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['NamespaceDecl', 'GlobalNamespace'],
		attributes: {
			sequence: ['abstract', 'final', 'globalId', 'internal', 'name', 'pragma'],
			details: {
				abstract: { default: 'false', facets: { whiteSpace: 'collapse' } },
				final: { default: 'false', facets: { whiteSpace: 'collapse' } },
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				internal: { default: 'false', facets: { whiteSpace: 'collapse' } },
				name: { required: true, facets: { whiteSpace: 'preserve' } },
				pragma: { facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: [
				'Documentation',
				'AddData',
				'UsingDirective',
				'Extends',
				'Implements',
				'Parameters',
				'ExternalVars',
				'Vars',
				'TempVars',
				'Method',
				'MainBody',
				'Action',
				'Transition',
			],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				Extends: { maxOccurs: 1 },
				Implements: {},
				Parameters: { maxOccurs: 1 },
				ExternalVars: {},
				Vars: {},
				TempVars: {},
				Method: {},
				MainBody: { maxOccurs: 1 },
				Action: {},
				Transition: {},
			},
		},
	},
	GlobalNamespace: {
		tag: 'GlobalNamespace',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Types'],
		attributes: {
			sequence: ['globalId', 'pragma'],
			details: {
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				pragma: { facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: [
				'Documentation',
				'AddData',
				'UsingDirective',
				'NamespaceDecl',
				'DataTypeDecl',
				'Program',
				'FunctionBlock',
				'Class',
				'Function',
				'Interface',
			],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				NamespaceDecl: { required: true, minOccurs: 1, maxOccurs: 1 },
				DataTypeDecl: { required: true, minOccurs: 1, maxOccurs: 1 },
				Program: { required: true, minOccurs: 1, maxOccurs: 1 },
				FunctionBlock: { required: true, minOccurs: 1, maxOccurs: 1 },
				Class: { required: true, minOccurs: 1, maxOccurs: 1 },
				Function: { required: true, minOccurs: 1, maxOccurs: 1 },
				Interface: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
			choices: [
				{
					options: ['Class', 'Function', 'FunctionBlock', 'Interface', 'Program'],
					minOccurs: 1,
					maxOccurs: 1,
				},
				{ options: ['PouDecl'], minOccurs: 1, maxOccurs: 1 },
				{ options: ['DataTypeDecl', 'NamespaceDecl', 'PouDecl'] },
			],
		},
	},
	GlobalVars: {
		tag: 'GlobalVars',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Program', 'Resource', 'Configuration'],
		attributes: {
			sequence: [
				'accessSpecifier',
				'constant',
				'globalId',
				'non_retain',
				'pragma',
				'retain',
				'xsi:type',
			],
			details: {
				accessSpecifier: {
					facets: {
						enumeration: ['private', 'protected', 'internal', 'public'],
						whiteSpace: 'preserve',
					},
				},
				constant: { default: 'false', facets: { whiteSpace: 'collapse' } },
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				non_retain: { default: 'false', facets: { whiteSpace: 'collapse' } },
				pragma: { facets: { whiteSpace: 'preserve' } },
				retain: { default: 'false', facets: { whiteSpace: 'collapse' } },
				'xsi:type': {
					namespace: { prefix: 'xsi', uri: 'http://www.w3.org/2001/XMLSchema-instance' },
					facets: { enumeration: ['VarListWithAccessSpec'] },
				},
			},
		},
		children: {
			sequence: ['Documentation', 'AddData', 'UsingDirective', 'Variable'],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				Variable: {},
			},
		},
	},
	GraphicalExpression: {
		tag: 'GraphicalExpression',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['GraphicalPredicate'],
		attributes: {
			sequence: ['evaluationOrder', 'globalId', 'label', 'xsi:type'],
			details: {
				evaluationOrder: {
					required: true,
					facets: { minInclusive: 0, maxInclusive: 18446744073709551615, whiteSpace: 'collapse' },
				},
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				label: { facets: { whiteSpace: 'preserve' } },
				'xsi:type': {
					namespace: { prefix: 'xsi', uri: 'http://www.w3.org/2001/XMLSchema-instance' },
					facets: { enumeration: ['FbdNetwork', 'LadderRung'] },
				},
			},
		},
		children: {
			sequence: [
				'Documentation',
				'AddData',
				'RelPosition',
				'Size',
				'CommonObject',
				'FbdObject',
				'LdObject',
			],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				RelPosition: { maxOccurs: 1 },
				Size: { maxOccurs: 1 },
				CommonObject: { maxOccurs: 1 },
				FbdObject: { maxOccurs: 1 },
				LdObject: { maxOccurs: 1 },
			},
		},
	},
	GraphicalPredicate: {
		tag: 'GraphicalPredicate',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Condition'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['ConnectionPointIn', 'GraphicalExpression'],
			details: {
				ConnectionPointIn: { required: true, minOccurs: 1, maxOccurs: 1 },
				GraphicalExpression: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
		},
	},
	IL: {
		tag: 'IL',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['BodyContent', 'PredicateContent'],
		attributes: {
			sequence: ['xsi:type'],
			details: {
				'xsi:type': {
					namespace: { prefix: 'xsi', uri: 'http://www.w3.org/2001/XMLSchema-instance' },
					facets: { enumeration: ['AccessSpecifiers', 'EdgeModifierType'] },
				},
			},
		},
		children: {
			sequence: [],
			details: {},
		},
		textContent: { facets: { whiteSpace: 'preserve' } },
	},
	Implements: {
		tag: 'Implements',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['FunctionBlock', 'Class'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['TypeName', 'InstantlyDefinedType'],
			details: {
				TypeName: { required: true, minOccurs: 1, maxOccurs: 1 },
				InstantlyDefinedType: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
			choices: [{ options: ['InstantlyDefinedType', 'TypeName'], minOccurs: 1, maxOccurs: 1 }],
		},
	},
	InOutAssignment: {
		tag: 'InOutAssignment',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['ProgramInstance'],
		attributes: {
			sequence: ['actualValue', 'formalParameter'],
			details: {
				actualValue: { required: true, facets: { whiteSpace: 'preserve' } },
				formalParameter: { required: true, facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: [],
			details: {},
		},
	},
	InOutVariable: {
		tag: 'InOutVariable',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['InOutVariables'],
		attributes: {
			sequence: ['globalId', 'negated', 'parameterName'],
			details: {
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				negated: { default: 'false', facets: { whiteSpace: 'collapse' } },
				parameterName: { required: true, facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: ['Documentation', 'AddData', 'ConnectionPointIn', 'ConnectionPointOut'],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				ConnectionPointIn: { maxOccurs: 1 },
				ConnectionPointOut: { maxOccurs: 1 },
			},
		},
	},
	InOutVariables: {
		tag: 'InOutVariables',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['FbdObject'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['InOutVariable'],
			details: {
				InOutVariable: {},
			},
		},
	},
	IndexRange: {
		tag: 'IndexRange',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['DimensionSpec'],
		attributes: {
			sequence: ['lower', 'upper'],
			details: {
				lower: { required: true, facets: { whiteSpace: 'preserve' } },
				upper: { required: true, facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: [],
			details: {},
		},
	},
	Info: {
		tag: 'Info',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['AddDataInfo'],
		attributes: {
			sequence: ['name', 'vendor', 'version'],
			details: {
				name: { required: true, facets: { whiteSpace: 'collapse' } },
				vendor: { required: true, facets: { whiteSpace: 'collapse' } },
				version: { facets: { whiteSpace: 'collapse' } },
			},
		},
		children: {
			sequence: ['Description'],
			details: {
				Description: { maxOccurs: 1 },
			},
		},
	},
	InitialValue: {
		tag: 'InitialValue',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['UserDefinedTypeSpec', 'Member', 'Variable', 'ConfigVariable'],
		attributes: {
			sequence: ['xsi:type'],
			details: {
				'xsi:type': {
					namespace: { prefix: 'xsi', uri: 'http://www.w3.org/2001/XMLSchema-instance' },
					facets: { enumeration: ['AccessSpecifiers', 'EdgeModifierType'] },
				},
			},
		},
		children: {
			sequence: ['SimpleValue', 'ArrayValue', 'StructValue'],
			details: {
				SimpleValue: { required: true, minOccurs: 1, maxOccurs: 1 },
				ArrayValue: { required: true, minOccurs: 1, maxOccurs: 1 },
				StructValue: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
			choices: [
				{ options: ['ArrayValue', 'SimpleValue', 'StructValue'], minOccurs: 1, maxOccurs: 1 },
			],
		},
	},
	Inline: {
		tag: 'Inline',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['ActionBlock'],
		attributes: {
			sequence: ['globalId', 'pragma'],
			details: {
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				pragma: { facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: ['Documentation', 'AddData', 'UsingDirective', 'BodyContent'],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				BodyContent: {},
			},
		},
	},
	InoutVars: {
		tag: 'InoutVars',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Parameters'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['Variable'],
			details: {
				Variable: {},
			},
		},
	},
	InputAssignment: {
		tag: 'InputAssignment',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['ProgramInstance'],
		attributes: {
			sequence: ['actualValue', 'formalParameter'],
			details: {
				actualValue: { required: true, facets: { whiteSpace: 'preserve' } },
				formalParameter: { required: true, facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: [],
			details: {},
		},
	},
	InputVariable: {
		tag: 'InputVariable',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['InputVariables'],
		attributes: {
			sequence: ['edge', 'globalId', 'negated', 'parameterName', 'suppressName'],
			details: {
				edge: {
					default: 'none',
					facets: { enumeration: ['none', 'falling', 'rising'], whiteSpace: 'preserve' },
				},
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				negated: { default: 'false', facets: { whiteSpace: 'collapse' } },
				parameterName: { required: true, facets: { whiteSpace: 'preserve' } },
				suppressName: { default: 'false', facets: { whiteSpace: 'collapse' } },
			},
		},
		children: {
			sequence: ['Documentation', 'AddData', 'ConnectionPointIn'],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				ConnectionPointIn: { maxOccurs: 1 },
			},
		},
	},
	InputVariables: {
		tag: 'InputVariables',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['FbdObject'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['InputVariable'],
			details: {
				InputVariable: {},
			},
		},
	},
	InputVars: {
		tag: 'InputVars',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Parameters'],
		attributes: {
			sequence: ['non_retain', 'retain'],
			details: {
				non_retain: { default: 'false', facets: { whiteSpace: 'collapse' } },
				retain: { default: 'false', facets: { whiteSpace: 'collapse' } },
			},
		},
		children: {
			sequence: ['Variable'],
			details: {
				Variable: {},
			},
		},
	},
	Instances: {
		tag: 'Instances',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Project'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['Configuration'],
			details: {
				Configuration: {},
			},
		},
	},
	InstantlyDefinedType: {
		tag: 'InstantlyDefinedType',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['BaseType', 'ReferenceTo', 'Type', 'Extends', 'Implements', 'ResultType'],
		attributes: {
			sequence: ['xsi:type'],
			details: {
				'xsi:type': {
					namespace: { prefix: 'xsi', uri: 'http://www.w3.org/2001/XMLSchema-instance' },
					facets: { enumeration: ['ArrayTypeSpec', 'ReferenceTypeSpec'] },
				},
			},
		},
		children: {
			sequence: ['BaseType', 'DimensionSpec', 'AddData', 'ReferenceTo'],
			details: {
				BaseType: { maxOccurs: 1 },
				DimensionSpec: {},
				AddData: { maxOccurs: 1 },
				ReferenceTo: { maxOccurs: 1 },
			},
		},
	},
	Interface: {
		tag: 'Interface',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['NamespaceDecl', 'GlobalNamespace'],
		attributes: {
			sequence: ['globalId', 'internal', 'name', 'pragma'],
			details: {
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				internal: { default: 'false', facets: { whiteSpace: 'collapse' } },
				name: { required: true, facets: { whiteSpace: 'preserve' } },
				pragma: { facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: ['Documentation', 'AddData', 'UsingDirective', 'Extends', 'Method'],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				Extends: {},
				Method: {},
			},
		},
	},
	LdObject: {
		tag: 'LdObject',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Rung', 'BodyContent', 'GraphicalExpression'],
		attributes: {
			sequence: [
				'compareOperator',
				'edge',
				'globalId',
				'latch',
				'negated',
				'operand',
				'operand1',
				'operand2',
				'xsi:type',
			],
			details: {
				compareOperator: {
					facets: { enumeration: ['>', '>=', '=', '<=', '<', '<>'], whiteSpace: 'preserve' },
				},
				edge: {
					default: 'none',
					facets: { enumeration: ['none', 'falling', 'rising'], whiteSpace: 'preserve' },
				},
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				latch: {
					default: 'none',
					facets: { enumeration: ['none', 'set', 'reset'], whiteSpace: 'preserve' },
				},
				negated: { default: 'false', facets: { whiteSpace: 'collapse' } },
				operand: { facets: { whiteSpace: 'preserve' } },
				operand1: { facets: { whiteSpace: 'preserve' } },
				operand2: { facets: { whiteSpace: 'preserve' } },
				'xsi:type': {
					namespace: { prefix: 'xsi', uri: 'http://www.w3.org/2001/XMLSchema-instance' },
					facets: {
						enumeration: ['Coil', 'CompareContact', 'Contact', 'LeftPowerRail', 'RightPowerRail'],
					},
				},
			},
		},
		children: {
			sequence: [
				'Documentation',
				'AddData',
				'RelPosition',
				'Size',
				'ConnectionPointIn',
				'ConnectionPointOut',
				'Type',
			],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				RelPosition: { maxOccurs: 1 },
				Size: { maxOccurs: 1 },
				ConnectionPointIn: { maxOccurs: 1 },
				ConnectionPointOut: { maxOccurs: 1 },
				Type: { maxOccurs: 1 },
			},
		},
	},
	LdScaling: {
		tag: 'LdScaling',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['CoordinateInfo'],
		attributes: {
			sequence: ['x', 'y'],
			details: {
				x: { required: true, facets: { whiteSpace: 'collapse' } },
				y: { required: true, facets: { whiteSpace: 'collapse' } },
			},
		},
		children: {
			sequence: [],
			details: {},
		},
	},
	MainBody: {
		tag: 'MainBody',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Program', 'FunctionBlock', 'Function'],
		attributes: {
			sequence: ['globalId', 'pragma'],
			details: {
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				pragma: { facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: ['Documentation', 'AddData', 'UsingDirective', 'BodyContent'],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				BodyContent: {},
			},
		},
	},
	Member: {
		tag: 'Member',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['UserDefinedTypeSpec'],
		attributes: {
			sequence: ['globalId', 'name', 'pragma'],
			details: {
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				name: { required: true, facets: { whiteSpace: 'preserve' } },
				pragma: { facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: ['Documentation', 'AddData', 'UsingDirective', 'Type', 'InitialValue', 'Address'],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				Type: { required: true, minOccurs: 1, maxOccurs: 1 },
				InitialValue: { maxOccurs: 1 },
				Address: { maxOccurs: 1 },
			},
		},
	},
	Method: {
		tag: 'Method',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['FunctionBlock', 'Class', 'Interface'],
		attributes: {
			sequence: ['abstract', 'accessSpecifier', 'final', 'globalId', 'name', 'override', 'pragma'],
			details: {
				abstract: { default: 'false', facets: { whiteSpace: 'collapse' } },
				accessSpecifier: {
					required: true,
					facets: {
						enumeration: ['private', 'protected', 'internal', 'public'],
						whiteSpace: 'preserve',
					},
				},
				final: { default: 'false', facets: { whiteSpace: 'collapse' } },
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				name: { required: true, facets: { whiteSpace: 'preserve' } },
				override: { default: 'false', facets: { whiteSpace: 'collapse' } },
				pragma: { facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: [
				'Documentation',
				'AddData',
				'UsingDirective',
				'ResultType',
				'Parameters',
				'TempVars',
				'Body',
			],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				ResultType: { maxOccurs: 1 },
				Parameters: { maxOccurs: 1 },
				TempVars: {},
				Body: { maxOccurs: 1 },
			},
		},
	},
	NamespaceDecl: {
		tag: 'NamespaceDecl',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['GlobalNamespace', 'NamespaceDecl'],
		attributes: {
			sequence: ['globalId', 'internal', 'name', 'pragma'],
			details: {
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				internal: { default: 'false', facets: { whiteSpace: 'collapse' } },
				name: { required: true, facets: { whiteSpace: 'preserve' } },
				pragma: { facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: [
				'Documentation',
				'AddData',
				'UsingDirective',
				'NamespaceDecl',
				'DataTypeDecl',
				'Program',
				'FunctionBlock',
				'Class',
				'Function',
				'Interface',
			],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				NamespaceDecl: { required: true, minOccurs: 1, maxOccurs: 1 },
				DataTypeDecl: { required: true, minOccurs: 1, maxOccurs: 1 },
				Program: { required: true, minOccurs: 1, maxOccurs: 1 },
				FunctionBlock: { required: true, minOccurs: 1, maxOccurs: 1 },
				Class: { required: true, minOccurs: 1, maxOccurs: 1 },
				Function: { required: true, minOccurs: 1, maxOccurs: 1 },
				Interface: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
			choices: [
				{
					options: ['Class', 'Function', 'FunctionBlock', 'Interface', 'Program'],
					minOccurs: 1,
					maxOccurs: 1,
				},
				{ options: ['PouDecl'], minOccurs: 1, maxOccurs: 1 },
				{ options: ['DataTypeDecl', 'NamespaceDecl', 'PouDecl'] },
			],
		},
	},
	Network: {
		tag: 'Network',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['BodyContent', 'PredicateContent'],
		attributes: {
			sequence: ['evaluationOrder', 'globalId', 'label'],
			details: {
				evaluationOrder: {
					required: true,
					facets: { minInclusive: 0, maxInclusive: 18446744073709551615, whiteSpace: 'collapse' },
				},
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				label: { facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: ['Documentation', 'AddData', 'RelPosition', 'Size', 'CommonObject', 'FbdObject'],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				RelPosition: { maxOccurs: 1 },
				Size: { maxOccurs: 1 },
				CommonObject: { required: true, minOccurs: 1, maxOccurs: 1 },
				FbdObject: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
			choices: [{ options: ['CommonObject', 'FbdObject'] }],
		},
	},
	OutputAssignment: {
		tag: 'OutputAssignment',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['ProgramInstance'],
		attributes: {
			sequence: ['actualValue', 'formalParameter'],
			details: {
				actualValue: { required: true, facets: { whiteSpace: 'preserve' } },
				formalParameter: { required: true, facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: [],
			details: {},
		},
	},
	OutputVariable: {
		tag: 'OutputVariable',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['OutputVariables'],
		attributes: {
			sequence: ['globalId', 'negated', 'parameterName', 'suppressName'],
			details: {
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				negated: { default: 'false', facets: { whiteSpace: 'collapse' } },
				parameterName: { required: true, facets: { whiteSpace: 'preserve' } },
				suppressName: { default: 'false', facets: { whiteSpace: 'collapse' } },
			},
		},
		children: {
			sequence: ['Documentation', 'AddData', 'ConnectionPointOut'],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				ConnectionPointOut: { maxOccurs: 1 },
			},
		},
	},
	OutputVariables: {
		tag: 'OutputVariables',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['FbdObject'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['OutputVariable'],
			details: {
				OutputVariable: {},
			},
		},
	},
	OutputVars: {
		tag: 'OutputVars',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Parameters'],
		attributes: {
			sequence: ['non_retain', 'retain'],
			details: {
				non_retain: { default: 'false', facets: { whiteSpace: 'collapse' } },
				retain: { default: 'false', facets: { whiteSpace: 'collapse' } },
			},
		},
		children: {
			sequence: ['Variable'],
			details: {
				Variable: {},
			},
		},
	},
	Parameters: {
		tag: 'Parameters',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Program', 'FunctionBlock', 'Method', 'Function'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['InoutVars', 'InputVars', 'OutputVars'],
			details: {
				InoutVars: { required: true, minOccurs: 1, maxOccurs: 1 },
				InputVars: { required: true, minOccurs: 1, maxOccurs: 1 },
				OutputVars: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
			choices: [{ options: ['InoutVars', 'InputVars', 'OutputVars'] }],
		},
	},
	PredicateContent: {
		tag: 'PredicateContent',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['TextualPredicate', 'Condition'],
		attributes: {
			sequence: ['xsi:type'],
			details: {
				'xsi:type': {
					namespace: { prefix: 'xsi', uri: 'http://www.w3.org/2001/XMLSchema-instance' },
					facets: { enumeration: ['FBD', 'IL', 'LD', 'ST'] },
				},
			},
		},
		children: {
			sequence: ['Network', 'IL', 'Rung', 'ST'],
			details: {
				Network: {},
				IL: { maxOccurs: 1 },
				Rung: {},
				ST: { maxOccurs: 1 },
			},
		},
	},
	Program: {
		tag: 'Program',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['NamespaceDecl', 'GlobalNamespace'],
		attributes: {
			sequence: ['globalId', 'internal', 'name', 'pragma'],
			details: {
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				internal: { default: 'false', facets: { whiteSpace: 'collapse' } },
				name: { required: true, facets: { whiteSpace: 'preserve' } },
				pragma: { facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: [
				'Documentation',
				'AddData',
				'UsingDirective',
				'AccessVars',
				'GlobalVars',
				'Parameters',
				'ExternalVars',
				'Vars',
				'TempVars',
				'MainBody',
				'Action',
				'Transition',
			],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				AccessVars: {},
				GlobalVars: {},
				Parameters: { maxOccurs: 1 },
				ExternalVars: {},
				Vars: {},
				TempVars: {},
				MainBody: { maxOccurs: 1 },
				Action: {},
				Transition: {},
			},
		},
	},
	ProgramInstance: {
		tag: 'ProgramInstance',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Resource'],
		attributes: {
			sequence: ['associatedTaskName', 'evaluationOrder', 'globalId', 'name', 'pragma', 'typeName'],
			details: {
				associatedTaskName: { facets: { whiteSpace: 'preserve' } },
				evaluationOrder: {
					facets: { minInclusive: 0, maxInclusive: 18446744073709551615, whiteSpace: 'collapse' },
				},
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				name: { required: true, facets: { whiteSpace: 'preserve' } },
				pragma: { facets: { whiteSpace: 'preserve' } },
				typeName: { required: true, facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: [
				'Documentation',
				'AddData',
				'UsingDirective',
				'InputAssignment',
				'OutputAssignment',
				'InOutAssignment',
				'FbInstTaskAssociation',
			],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				InputAssignment: {},
				OutputAssignment: {},
				InOutAssignment: {},
				FbInstTaskAssociation: {},
			},
		},
	},
	Project: {
		tag: 'Project',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: [],
		attributes: {
			sequence: ['schemaVersion'],
			details: {
				schemaVersion: { required: true, facets: { whiteSpace: 'collapse' } },
			},
		},
		children: {
			sequence: ['FileHeader', 'ContentHeader', 'Types', 'Instances', 'AddData', 'Documentation'],
			details: {
				FileHeader: { required: true, minOccurs: 1, maxOccurs: 1 },
				ContentHeader: { required: true, minOccurs: 1, maxOccurs: 1 },
				Types: { required: true, minOccurs: 1, maxOccurs: 1 },
				Instances: { required: true, minOccurs: 1, maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				Documentation: { maxOccurs: 1 },
			},
		},
	},
	Range: {
		tag: 'Range',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['UserDefinedTypeSpec'],
		attributes: {
			sequence: ['lower', 'upper'],
			details: {
				lower: { required: true, facets: { whiteSpace: 'preserve' } },
				upper: { required: true, facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: [],
			details: {},
		},
	},
	Reference: {
		tag: 'Reference',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Condition'],
		attributes: {
			sequence: ['name'],
			details: {
				name: { required: true, facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: [],
			details: {},
		},
	},
	ReferenceName: {
		tag: 'ReferenceName',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['ActionBlock'],
		attributes: {
			sequence: ['xsi:type'],
			details: {
				'xsi:type': {
					namespace: { prefix: 'xsi', uri: 'http://www.w3.org/2001/XMLSchema-instance' },
					facets: { enumeration: ['AccessSpecifiers', 'EdgeModifierType'] },
				},
			},
		},
		children: {
			sequence: [],
			details: {},
		},
		textContent: { facets: { whiteSpace: 'preserve' } },
	},
	ReferenceTo: {
		tag: 'ReferenceTo',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['InstantlyDefinedType', 'UserDefinedTypeSpec'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['TypeName', 'InstantlyDefinedType'],
			details: {
				TypeName: { required: true, minOccurs: 1, maxOccurs: 1 },
				InstantlyDefinedType: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
			choices: [{ options: ['InstantlyDefinedType', 'TypeName'], minOccurs: 1, maxOccurs: 1 }],
		},
	},
	RelPosition: {
		tag: 'RelPosition',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: [
			'Network',
			'CommonObject',
			'ConnectionPointIn',
			'Connection',
			'FeedbackConnection',
			'ActionBlock',
			'ConnectionPointOut',
			'FbdObject',
			'Rung',
			'LdObject',
			'SfcObject',
			'ConnectionPointOutAction',
			'GraphicalExpression',
		],
		attributes: {
			sequence: ['x', 'y'],
			details: {
				x: { required: true, facets: { whiteSpace: 'collapse' } },
				y: { required: true, facets: { whiteSpace: 'collapse' } },
			},
		},
		children: {
			sequence: [],
			details: {},
		},
	},
	Resource: {
		tag: 'Resource',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Configuration'],
		attributes: {
			sequence: ['globalId', 'name', 'pragma', 'resourceTypeName'],
			details: {
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				name: { required: true, facets: { whiteSpace: 'preserve' } },
				pragma: { facets: { whiteSpace: 'preserve' } },
				resourceTypeName: { required: true, facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: [
				'Documentation',
				'AddData',
				'UsingDirective',
				'GlobalVars',
				'Task',
				'ProgramInstance',
			],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				GlobalVars: {},
				Task: {},
				ProgramInstance: {},
			},
		},
	},
	ResultType: {
		tag: 'ResultType',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Method', 'Function'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['TypeName', 'InstantlyDefinedType'],
			details: {
				TypeName: { required: true, minOccurs: 1, maxOccurs: 1 },
				InstantlyDefinedType: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
			choices: [{ options: ['InstantlyDefinedType', 'TypeName'], minOccurs: 1, maxOccurs: 1 }],
		},
	},
	Rung: {
		tag: 'Rung',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['BodyContent', 'PredicateContent'],
		attributes: {
			sequence: ['evaluationOrder', 'globalId', 'label'],
			details: {
				evaluationOrder: {
					required: true,
					facets: { minInclusive: 0, maxInclusive: 18446744073709551615, whiteSpace: 'collapse' },
				},
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				label: { facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: [
				'Documentation',
				'AddData',
				'RelPosition',
				'Size',
				'CommonObject',
				'LdObject',
				'FbdObject',
			],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				RelPosition: { maxOccurs: 1 },
				Size: { maxOccurs: 1 },
				CommonObject: { required: true, minOccurs: 1, maxOccurs: 1 },
				LdObject: { required: true, minOccurs: 1, maxOccurs: 1 },
				FbdObject: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
			choices: [{ options: ['CommonObject', 'FbdObject', 'LdObject'] }],
		},
	},
	ST: {
		tag: 'ST',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['PredicateContent', 'BodyContent'],
		attributes: {
			sequence: ['xsi:type'],
			details: {
				'xsi:type': {
					namespace: { prefix: 'xsi', uri: 'http://www.w3.org/2001/XMLSchema-instance' },
					facets: { enumeration: ['AccessSpecifiers', 'EdgeModifierType'] },
				},
			},
		},
		children: {
			sequence: [],
			details: {},
		},
		textContent: { facets: { whiteSpace: 'preserve' } },
	},
	SfcObject: {
		tag: 'SfcObject',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['BodyContent'],
		attributes: {
			sequence: ['globalId', 'initialStep', 'mutualExclusion', 'name', 'xsi:type'],
			details: {
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				initialStep: { default: 'false', facets: { whiteSpace: 'collapse' } },
				mutualExclusion: { default: 'false', facets: { whiteSpace: 'collapse' } },
				name: { facets: { whiteSpace: 'preserve' } },
				'xsi:type': {
					namespace: { prefix: 'xsi', uri: 'http://www.w3.org/2001/XMLSchema-instance' },
					facets: {
						enumeration: [
							'SelectionConvergence',
							'SelectionDivergence',
							'SimultaneousConvergence',
							'SimultaneousDivergence',
							'Step',
							'Transition',
						],
					},
				},
			},
		},
		children: {
			sequence: [
				'Documentation',
				'AddData',
				'RelPosition',
				'Size',
				'ConnectionPointIn',
				'ConnectionPointOut',
				'ConnectionPointOutAction',
				'Condition',
			],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				RelPosition: { maxOccurs: 1 },
				Size: { maxOccurs: 1 },
				ConnectionPointIn: {},
				ConnectionPointOut: { maxOccurs: 1 },
				ConnectionPointOutAction: { maxOccurs: 1 },
				Condition: { maxOccurs: 1 },
			},
		},
	},
	SfcScaling: {
		tag: 'SfcScaling',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['CoordinateInfo'],
		attributes: {
			sequence: ['x', 'y'],
			details: {
				x: { required: true, facets: { whiteSpace: 'collapse' } },
				y: { required: true, facets: { whiteSpace: 'collapse' } },
			},
		},
		children: {
			sequence: [],
			details: {},
		},
	},
	SimpleValue: {
		tag: 'SimpleValue',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['InitialValue', 'Value'],
		attributes: {
			sequence: ['value'],
			details: {
				value: { facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: [],
			details: {},
		},
	},
	Size: {
		tag: 'Size',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: [
			'Network',
			'CommonObject',
			'ActionBlock',
			'FbdObject',
			'Rung',
			'LdObject',
			'SfcObject',
			'GraphicalExpression',
		],
		attributes: {
			sequence: ['x', 'y'],
			details: {
				x: { required: true, facets: { whiteSpace: 'collapse' } },
				y: { required: true, facets: { whiteSpace: 'collapse' } },
			},
		},
		children: {
			sequence: [],
			details: {},
		},
	},
	StructValue: {
		tag: 'StructValue',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Value', 'InitialValue'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['Value'],
			details: {
				Value: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
		},
	},
	Task: {
		tag: 'Task',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Resource'],
		attributes: {
			sequence: ['globalId', 'interval', 'name', 'pragma', 'priority', 'single', 'xsi:type'],
			details: {
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				interval: { facets: { whiteSpace: 'preserve' } },
				name: { required: true, facets: { whiteSpace: 'preserve' } },
				pragma: { facets: { whiteSpace: 'preserve' } },
				priority: { facets: { minInclusive: 0, maxInclusive: 65535, whiteSpace: 'collapse' } },
				single: { facets: { whiteSpace: 'preserve' } },
				'xsi:type': {
					namespace: { prefix: 'xsi', uri: 'http://www.w3.org/2001/XMLSchema-instance' },
					facets: { enumeration: ['StandardTask'] },
				},
			},
		},
		children: {
			sequence: ['Documentation', 'AddData', 'UsingDirective'],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
			},
		},
	},
	TempVars: {
		tag: 'TempVars',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Program', 'FunctionBlock', 'Method', 'Function'],
		attributes: {
			sequence: [
				'accessSpecifier',
				'constant',
				'globalId',
				'non_retain',
				'pragma',
				'retain',
				'xsi:type',
			],
			details: {
				accessSpecifier: {
					facets: {
						enumeration: ['private', 'protected', 'internal', 'public'],
						whiteSpace: 'preserve',
					},
				},
				constant: { default: 'false', facets: { whiteSpace: 'collapse' } },
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				non_retain: { default: 'false', facets: { whiteSpace: 'collapse' } },
				pragma: { facets: { whiteSpace: 'preserve' } },
				retain: { default: 'false', facets: { whiteSpace: 'collapse' } },
				'xsi:type': {
					namespace: { prefix: 'xsi', uri: 'http://www.w3.org/2001/XMLSchema-instance' },
					facets: { enumeration: ['VarListWithAccessSpec'] },
				},
			},
		},
		children: {
			sequence: ['Documentation', 'AddData', 'UsingDirective', 'Variable'],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				Variable: {},
			},
		},
	},
	TextualPredicate: {
		tag: 'TextualPredicate',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Condition'],
		attributes: {
			sequence: ['globalId', 'pragma'],
			details: {
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				pragma: { facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: ['Documentation', 'AddData', 'UsingDirective', 'PredicateContent'],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				PredicateContent: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
		},
	},
	Transition: {
		tag: 'Transition',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Program', 'FunctionBlock'],
		attributes: {
			sequence: ['globalId', 'name', 'pragma'],
			details: {
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				name: { required: true, facets: { whiteSpace: 'preserve' } },
				pragma: { facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: ['Documentation', 'AddData', 'UsingDirective', 'Condition'],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				Condition: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
		},
	},
	Type: {
		tag: 'Type',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Member', 'Variable', 'LdObject', 'AccessVariable', 'ConfigVariable'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['TypeName', 'InstantlyDefinedType'],
			details: {
				TypeName: { required: true, minOccurs: 1, maxOccurs: 1 },
				InstantlyDefinedType: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
			choices: [{ options: ['InstantlyDefinedType', 'TypeName'], minOccurs: 1, maxOccurs: 1 }],
		},
	},
	TypeName: {
		tag: 'TypeName',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['BaseType', 'ReferenceTo', 'Type', 'Extends', 'Implements', 'ResultType'],
		attributes: {
			sequence: ['xsi:type'],
			details: {
				'xsi:type': {
					namespace: { prefix: 'xsi', uri: 'http://www.w3.org/2001/XMLSchema-instance' },
					facets: { enumeration: ['AccessSpecifiers', 'EdgeModifierType'] },
				},
			},
		},
		children: {
			sequence: [],
			details: {},
		},
		textContent: { facets: { whiteSpace: 'preserve' } },
	},
	Types: {
		tag: 'Types',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Project'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['GlobalNamespace'],
			details: {
				GlobalNamespace: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
		},
	},
	UserDefinedTypeSpec: {
		tag: 'UserDefinedTypeSpec',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['DataTypeDecl'],
		attributes: {
			sequence: ['overlap', 'xsi:type'],
			details: {
				overlap: { default: 'false', facets: { whiteSpace: 'collapse' } },
				'xsi:type': {
					namespace: { prefix: 'xsi', uri: 'http://www.w3.org/2001/XMLSchema-instance' },
					facets: {
						enumeration: [
							'ArrayTypeSpec',
							'DirectlyDerivedTypeSpec',
							'EnumTypeSpec',
							'EnumTypeWithNamedValueSpec',
							'ReferenceTypeSpec',
							'StructTypeSpec',
							'SubrangeTypeSpec',
						],
					},
				},
			},
		},
		children: {
			sequence: [
				'BaseType',
				'DimensionSpec',
				'AddData',
				'InitialValue',
				'Enumerator',
				'ReferenceTo',
				'Member',
				'Range',
			],
			details: {
				BaseType: { maxOccurs: 1 },
				DimensionSpec: {},
				AddData: { maxOccurs: 1 },
				InitialValue: { maxOccurs: 1 },
				Enumerator: {},
				ReferenceTo: { maxOccurs: 1 },
				Member: {},
				Range: { maxOccurs: 1 },
			},
		},
	},
	UsingDirective: {
		tag: 'UsingDirective',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: [
			'GlobalNamespace',
			'NamespaceDecl',
			'DataTypeDecl',
			'Member',
			'Address',
			'Program',
			'AccessVars',
			'Variable',
			'GlobalVars',
			'ExternalVars',
			'Vars',
			'TempVars',
			'MainBody',
			'Inline',
			'TextualPredicate',
			'Action',
			'Body',
			'Transition',
			'Condition',
			'FunctionBlock',
			'Method',
			'Class',
			'Function',
			'Interface',
			'Configuration',
			'Resource',
			'Task',
			'ProgramInstance',
			'AccessVariable',
			'ConfigVars',
			'ConfigVariable',
		],
		attributes: {
			sequence: ['xsi:type'],
			details: {
				'xsi:type': {
					namespace: { prefix: 'xsi', uri: 'http://www.w3.org/2001/XMLSchema-instance' },
					facets: { enumeration: ['AccessSpecifiers', 'EdgeModifierType'] },
				},
			},
		},
		children: {
			sequence: [],
			details: {},
		},
		textContent: { facets: { whiteSpace: 'preserve' } },
	},
	Value: {
		tag: 'Value',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['ArrayValue', 'StructValue'],
		attributes: {
			sequence: ['repetitionValue'],
			details: {
				repetitionValue: { default: '1', facets: { whiteSpace: 'preserve' } },
			},
		},
		children: {
			sequence: ['SimpleValue', 'ArrayValue', 'StructValue'],
			details: {
				SimpleValue: { required: true, minOccurs: 1, maxOccurs: 1 },
				ArrayValue: { required: true, minOccurs: 1, maxOccurs: 1 },
				StructValue: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
			choices: [
				{ options: ['ArrayValue', 'SimpleValue', 'StructValue'], minOccurs: 1, maxOccurs: 1 },
			],
		},
	},
	Variable: {
		tag: 'Variable',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: [
			'AccessVars',
			'GlobalVars',
			'InoutVars',
			'InputVars',
			'OutputVars',
			'ExternalVars',
			'Vars',
			'TempVars',
		],
		attributes: {
			sequence: ['globalId', 'name', 'pragma', 'xsi:type'],
			details: {
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				name: { required: true, facets: { whiteSpace: 'preserve' } },
				pragma: { facets: { whiteSpace: 'preserve' } },
				'xsi:type': {
					namespace: { prefix: 'xsi', uri: 'http://www.w3.org/2001/XMLSchema-instance' },
					facets: { enumeration: ['VariableDecl'] },
				},
			},
		},
		children: {
			sequence: ['Documentation', 'AddData', 'UsingDirective', 'Type', 'InitialValue', 'Address'],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				Type: { required: true, minOccurs: 1, maxOccurs: 1 },
				InitialValue: { maxOccurs: 1 },
				Address: { maxOccurs: 1 },
			},
		},
	},
	VariableLength: {
		tag: 'VariableLength',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['DimensionSpec'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: [],
			details: {},
		},
		textContent: { facets: { whiteSpace: 'collapse' } },
	},
	Vars: {
		tag: 'Vars',
		namespace: { prefix: 'ppx', uri: 'www.iec.ch/public/TC65SC65BWG7TF10' },
		parents: ['Program', 'FunctionBlock', 'Class'],
		attributes: {
			sequence: ['accessSpecifier', 'constant', 'globalId', 'non_retain', 'pragma', 'retain'],
			details: {
				accessSpecifier: {
					required: true,
					facets: {
						enumeration: ['private', 'protected', 'internal', 'public'],
						whiteSpace: 'preserve',
					},
				},
				constant: { default: 'false', facets: { whiteSpace: 'collapse' } },
				globalId: {
					facets: {
						pattern: ['[[A-Za-z_:]-[:]][[-.:0-9A-Z_a-z]-[:]]*', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						whiteSpace: 'collapse',
					},
				},
				non_retain: { default: 'false', facets: { whiteSpace: 'collapse' } },
				pragma: { facets: { whiteSpace: 'preserve' } },
				retain: { default: 'false', facets: { whiteSpace: 'collapse' } },
			},
		},
		children: {
			sequence: ['Documentation', 'AddData', 'UsingDirective', 'Variable'],
			details: {
				Documentation: { maxOccurs: 1 },
				AddData: { maxOccurs: 1 },
				UsingDirective: {},
				Variable: {},
			},
		},
	},
} as const
