// Auto-generated by generate.py — do not edit

import type { ELEMENT_NAMES, REQUIRED_ATTRIBUTES } from './constants.generated'

export type AvailableElement = (typeof ELEMENT_NAMES)[number]

export type AttributesAccessVariable = {
	alias: string
	direction?: 'readOnly' | 'readWrite' | (string & {})
	globalId?: string
	instancePathAndName: string
	pragma?: string
}

export type AttributesAccessVars = {
	constant?: string
	globalId?: string
	non_retain?: string
	pragma?: string
	retain?: string
}

export type AttributesAction = {
	globalId?: string
	name: string
	pragma?: string
}

export type AttributesAddData = {
}

export type AttributesAddDataInfo = {
}

export type AttributesAddress = {
	address?: string
	globalId?: string
	location?: 'I' | 'Q' | 'M' | (string & {})
	notYetFixed?: string
	pragma?: string
	size?: 'X' | 'B' | 'W' | 'D' | 'L' | (string & {})
}

export type AttributesArrayValue = {
}

export type AttributesBody = {
	globalId?: string
	pragma?: string
}

export type AttributesBodyContent = {
}

export type AttributesClass = {
	abstract?: string
	final?: string
	globalId?: string
	internal?: string
	name: string
	pragma?: string
}

export type AttributesCondition = {
	globalId?: string
	pragma?: string
}

export type AttributesConfigVariable = {
	globalId?: string
	instancePathAndName: string
	pragma?: string
}

export type AttributesConfigVars = {
	globalId?: string
	pragma?: string
}

export type AttributesConfiguration = {
	globalId?: string
	name: string
	pragma?: string
}

export type AttributesContentHeader = {
	author?: string
	creationDateTime: string
	language?: string
	modificationDateTime?: string
	name: string
	organization?: string
	version?: string
}

export type AttributesCoordinateInfo = {
}

export type AttributesData = {
	handleUnknown: 'preserve' | 'discard' | 'implementation' | (string & {})
	name: string
}

export type AttributesDataTypeDecl = {
	globalId?: string
	internal?: string
	name: string
	pragma?: string
}

export type AttributesDescription = {
}

export type AttributesDocumentation = {
}

export type AttributesExtends = {
}

export type AttributesExternalVars = {
	constant?: string
	globalId?: string
	pragma?: string
}

export type AttributesFbInstTaskAssociation = {
	associatedTaskName: string
	fbInstanceName: string
}

export type AttributesFbdScaling = {
	x: string
	y: string
}

export type AttributesFileHeader = {
	companyName: string
	companyURL?: string
	productName: string
	productRelease?: string
	productVersion: string
}

export type AttributesFunction = {
	globalId?: string
	internal?: string
	name: string
	pragma?: string
}

export type AttributesFunctionBlock = {
	abstract?: string
	final?: string
	globalId?: string
	internal?: string
	name: string
	pragma?: string
}

export type AttributesGlobalNamespace = {
	globalId?: string
	pragma?: string
}

export type AttributesGlobalVars = {
	constant?: string
	globalId?: string
	non_retain?: string
	pragma?: string
	retain?: string
}

export type AttributesImplements = {
}

export type AttributesInOutAssignment = {
	actualValue: string
	formalParameter: string
}

export type AttributesInfo = {
	name: string
	vendor: string
	version?: string
}

export type AttributesInitialValue = {
}

export type AttributesInoutVars = {
}

export type AttributesInputAssignment = {
	actualValue: string
	formalParameter: string
}

export type AttributesInputVars = {
	non_retain?: string
	retain?: string
}

export type AttributesInstances = {
}

export type AttributesInstantlyDefinedType = {
}

export type AttributesInterface = {
	globalId?: string
	internal?: string
	name: string
	pragma?: string
}

export type AttributesLdScaling = {
	x: string
	y: string
}

export type AttributesMainBody = {
	globalId?: string
	pragma?: string
}

export type AttributesMethod = {
	abstract?: string
	accessSpecifier: 'private' | 'protected' | 'internal' | 'public' | (string & {})
	final?: string
	globalId?: string
	name: string
	override?: string
	pragma?: string
}

export type AttributesNamespaceDecl = {
	globalId?: string
	internal?: string
	name: string
	pragma?: string
}

export type AttributesOutputAssignment = {
	actualValue: string
	formalParameter: string
}

export type AttributesOutputVars = {
	non_retain?: string
	retain?: string
}

export type AttributesParameters = {
}

export type AttributesPredicateContent = {
}

export type AttributesProgram = {
	globalId?: string
	internal?: string
	name: string
	pragma?: string
}

export type AttributesProgramInstance = {
	associatedTaskName?: string
	evaluationOrder?: string
	globalId?: string
	name: string
	pragma?: string
	typeName: string
}

export type AttributesProject = {
	schemaVersion: string
}

export type AttributesResource = {
	globalId?: string
	name: string
	pragma?: string
	resourceTypeName: string
}

export type AttributesResultType = {
}

export type AttributesSfcScaling = {
	x: string
	y: string
}

export type AttributesSimpleValue = {
	value?: string
}

export type AttributesStructValue = {
}

export type AttributesTask = {
	globalId?: string
	name: string
	pragma?: string
}

export type AttributesTempVars = {
	constant?: string
	globalId?: string
	non_retain?: string
	pragma?: string
	retain?: string
}

export type AttributesTransition = {
	globalId?: string
	name: string
	pragma?: string
}

export type AttributesType = {
}

export type AttributesTypeName = {
}

export type AttributesTypes = {
}

export type AttributesUserDefinedTypeSpec = {
}

export type AttributesUsingDirective = {
}

export type AttributesValue = {
	repetitionValue?: string
}

export type AttributesVariable = {
	globalId?: string
	name: string
	pragma?: string
}

export type AttributesVars = {
	accessSpecifier: 'private' | 'protected' | 'internal' | 'public' | (string & {})
	constant?: string
	globalId?: string
	non_retain?: string
	pragma?: string
	retain?: string
}

export type AttributesMap = {
	AccessVariable: AttributesAccessVariable
	AccessVars: AttributesAccessVars
	Action: AttributesAction
	AddData: AttributesAddData
	AddDataInfo: AttributesAddDataInfo
	Address: AttributesAddress
	ArrayValue: AttributesArrayValue
	Body: AttributesBody
	BodyContent: AttributesBodyContent
	Class: AttributesClass
	Condition: AttributesCondition
	ConfigVariable: AttributesConfigVariable
	ConfigVars: AttributesConfigVars
	Configuration: AttributesConfiguration
	ContentHeader: AttributesContentHeader
	CoordinateInfo: AttributesCoordinateInfo
	Data: AttributesData
	DataTypeDecl: AttributesDataTypeDecl
	Description: AttributesDescription
	Documentation: AttributesDocumentation
	Extends: AttributesExtends
	ExternalVars: AttributesExternalVars
	FbInstTaskAssociation: AttributesFbInstTaskAssociation
	FbdScaling: AttributesFbdScaling
	FileHeader: AttributesFileHeader
	Function: AttributesFunction
	FunctionBlock: AttributesFunctionBlock
	GlobalNamespace: AttributesGlobalNamespace
	GlobalVars: AttributesGlobalVars
	Implements: AttributesImplements
	InOutAssignment: AttributesInOutAssignment
	Info: AttributesInfo
	InitialValue: AttributesInitialValue
	InoutVars: AttributesInoutVars
	InputAssignment: AttributesInputAssignment
	InputVars: AttributesInputVars
	Instances: AttributesInstances
	InstantlyDefinedType: AttributesInstantlyDefinedType
	Interface: AttributesInterface
	LdScaling: AttributesLdScaling
	MainBody: AttributesMainBody
	Method: AttributesMethod
	NamespaceDecl: AttributesNamespaceDecl
	OutputAssignment: AttributesOutputAssignment
	OutputVars: AttributesOutputVars
	Parameters: AttributesParameters
	PredicateContent: AttributesPredicateContent
	Program: AttributesProgram
	ProgramInstance: AttributesProgramInstance
	Project: AttributesProject
	Resource: AttributesResource
	ResultType: AttributesResultType
	SfcScaling: AttributesSfcScaling
	SimpleValue: AttributesSimpleValue
	StructValue: AttributesStructValue
	Task: AttributesTask
	TempVars: AttributesTempVars
	Transition: AttributesTransition
	Type: AttributesType
	TypeName: AttributesTypeName
	Types: AttributesTypes
	UserDefinedTypeSpec: AttributesUserDefinedTypeSpec
	UsingDirective: AttributesUsingDirective
	Value: AttributesValue
	Variable: AttributesVariable
	Vars: AttributesVars
}

export type AttributesOf<T extends AvailableElement> = AttributesMap[T]

export type RequiredAttributeNames<T extends AvailableElement> =
	(typeof REQUIRED_ATTRIBUTES)[T][number]
export type OptionalAttributeNames<T extends AvailableElement> = Exclude<
	keyof AttributesOf<T>,
	RequiredAttributeNames<T>
>
